### ISSUE TITLE
[BUG] <title>Custom indicator display BUG

### ISSUE THREAD

**Issue by Tianyaya1** [apache/hertzbeat#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/dromara/hertzbeat/assets/139327121/33ff9d7f-d93d-42b8-b2e7-b480d81ae423)
这个是我自定义的指标，sql查出来是一个结果集，我在2点的时候查询出来30条数据，显示30条数据，指标正常，但是我现在10点查出来结果集为0条数据，显示的还是2点查询的30条数据,正常应该是展示0条数据

### Expected Behavior

目前手动解决这个问题的方法只有手动修改监控模板的指标名称，这样重新采集的是正确数据，例如 table_locked修改为table+locked，而且不能用历史指标名称，否则还会展示历史数据
![image](https://github.com/dromara/hertzbeat/assets/139327121/67bb0a9e-0936-474a-a44d-3616c1dea978)

### Steps To Reproduce

![image](https://github.com/dromara/hertzbeat/assets/139327121/511d419c-3f12-415c-89f4-1265c8108311)
这个是我配置的监控模板

### Environment

```markdown
HertzBeat version(s):1.3.2
```

**Comment by Aias00** [comment]
assign me, pls

**Comment by tomsun28** [comment]
maybe cause by here 

https://github.com/apache/hertzbeat/blob/master/warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/realtime/memory/MemoryDataStorage.java#L75

https://github.com/apache/hertzbeat/blob/master/warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/realtime/redis/RedisDataStorage.java#L82

**Comment by Aias00** [comment]
> maybe cause by here
> 
> https://github.com/apache/hertzbeat/blob/master/warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/realtime/memory/MemoryDataStorage.java#L75
> 
> https://github.com/apache/hertzbeat/blob/master/warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/realtime/redis/RedisDataStorage.java#L82

I have dealed with above-mentioned logic and i had submit a pr. 
but i still have questions, which is "wether the history store saveData method should handle the empty value?"
