### ISSUE TITLE
[Task] Dashboard TOP n display <title>

### ISSUE THREAD

**Issue by COCONUTYA1** [apache/hertzbeat#1219]
### Description

希望仪表盘增加TOP n显示面板，如cpu 使用top 10、内存使用top10、磁盘top 10等

### Task List

- [ ] 仪表盘增加TOP n显示面板

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

It is hoped that the dashboard will add a TOP n display panel, such as cpu usage top 10, memory usage top 10, disk top 10, etc.

### Task List

- [ ] Dashboard adds TOP n display panel

**Comment by YxYL6125** [comment]
plz assign to me

**Comment by tomsun28** [comment]
We can not add this sir, it will looks strange @YxYL6125

**Comment by YxYL6125** [comment]
> strange

got it
