### ISSUE TITLE
Discussion for OSPP and Project Setup Issue

### ISSUE THREAD

**Issue by bhutani2002** [apache/hertzbeat#143]
Hey I am Raag Bhutani, a Computer Science undergrad at University Institute of Engineering Technology, Panjab University, India, and a keen enthusiast in web development.

I am interested in contributing to "**Hertzbeat official website UI revision and document i18n**" project.

**However I am having some difficulties in setting up the project .** 

I am trying to set up the project through "Method 1: Quick installation by Docker". After  setting up docker on desktop and  pulling out the HertzBeat Docker image , and after running

**Command** :  "docker run -d -p 1157:1157 -v /opt/application.yml:/opt/hertzbeat/config/application.yml -v /opt/sureness.yml:/opt/hertzbeat/config/sureness.yml --name hertzbeat tancloud/hertzbeat:[版本tag] 526aa188da767ae94b244226a2b2eec2b5f17dd8eff592893d9ec0cd0f3a1ccd" by changing the path too : "Error response from daemon: invalid mode: /Projects/OSPP/hertzbeat-1.0-beta.8/script/application.yml."

Probably there's something to do with application.yml file. 

And I can't figure out how to communicate with the community, as WeChat exchange group and QQ exchange group aren't working.
Does the community have slack, zulip ,etc, through which I can communicate with the mentors for the OSPP program. 

I would be really grateful if I could get some help on this and directions to work on this project.

Thank You

**Comment by tomsun28** [comment]
hi welcome, you can contact the project mentor  @shimingxy using email [shimh@maxsso.net](mailto:shimh@maxsso.net) , or discuss in  https://github.com/dromara/hertzbeat/discussions , we will open slack later.   

> **However I am having some difficulties in setting up the project .**
> 
> I am trying to set up the project through "Method 1: Quick installation by Docker". After setting up docker on desktop and pulling out the HertzBeat Docker image , and after running
> 
> **Command** : "docker run -d -p 1157:1157 -v /opt/application.yml:/opt/hertzbeat/config/application.yml -v /opt/sureness.yml:/opt/hertzbeat/config/sureness.yml --name hertzbeat tancloud/hertzbeat:[版本tag] 526aa188da767ae94b244226a2b2eec2b5f17dd8eff592893d9ec0cd0f3a1ccd" by changing the path too : "Error response from daemon: invalid mode: /Projects/OSPP/hertzbeat-1.0-beta.8/script/application.yml."
> 
> Probably there's something to do with application.yml file.

HertzBeat depends at least on relational database [MYSQL5+](https://www.mysql.com/) and time series database [TDengine2+](https://www.taosdata.com/getting-started) (optional), and we should config the application.yml or the sureness.yml(optional) in local machine before `docker run`   

here is the quickstart document https://hertzbeat.com/en/docs/start/quickstart    

best wish

**Comment by bhutani2002** [comment]
Thank You so much for the response

> hi welcome, you can contact the project mentor @shimingxy using email [shimh@maxsso.net](mailto:shimh@maxsso.net) , or discuss in https://github.com/dromara/hertzbeat/discussions , we will open slack later.
> 
> > **However I am having some difficulties in setting up the project .**
> > I am trying to set up the project through "Method 1: Quick installation by Docker". After setting up docker on desktop and pulling out the HertzBeat Docker image , and after running
> > **Command** : "docker run -d -p 1157:1157 -v /opt/application.yml:/opt/hertzbeat/config/application.yml -v /opt/sureness.yml:/opt/hertzbeat/config/sureness.yml --name hertzbeat tancloud/hertzbeat:[版本tag] 526aa188da767ae94b244226a2b2eec2b5f17dd8eff592893d9ec0cd0f3a1ccd" by changing the path too : "Error response from daemon: invalid mode: /Projects/OSPP/hertzbeat-1.0-beta.8/script/application.yml."
> > Probably there's something to do with application.yml file.
> 
> HertzBeat depends at least on relational database [MYSQL5+](https://www.mysql.com/) and time series database [TDengine2+](https://www.taosdata.com/getting-started) (optional), and we should config the application.yml or the sureness.yml(optional) in local machine before `docker run`
> 
> here is the quickstart document https://hertzbeat.com/en/docs/start/quickstart
> 
> best wish

Thank you so much for the response.

**Comment by psankhe28** [comment]
> Hey I am Raag Bhutani, a Computer Science undergrad at University Institute of Engineering Technology, Panjab University, India, and a keen enthusiast in web development.
> 
> I am interested in contributing to "**Hertzbeat official website UI revision and document i18n**" project.
> 
> **However I am having some difficulties in setting up the project .**
> 
> I am trying to set up the project through "Method 1: Quick installation by Docker". After setting up docker on desktop and pulling out the HertzBeat Docker image , and after running
> 
> **Command** : "docker run -d -p 1157:1157 -v /opt/application.yml:/opt/hertzbeat/config/application.yml -v /opt/sureness.yml:/opt/hertzbeat/config/sureness.yml --name hertzbeat tancloud/hertzbeat:[版本tag] 526aa188da767ae94b244226a2b2eec2b5f17dd8eff592893d9ec0cd0f3a1ccd" by changing the path too : "Error response from daemon: invalid mode: /Projects/OSPP/hertzbeat-1.0-beta.8/script/application.yml."
> 
> Probably there's something to do with application.yml file.
> 
> And I can't figure out how to communicate with the community, as WeChat exchange group and QQ exchange group aren't working. Does the community have slack, zulip ,etc, through which I can communicate with the mentors for the OSPP program.
> 
> I would be really grateful if I could get some help on this and directions to work on this project.
> 
> Thank You

Were you able to install it? I am still facing an issue
