### ISSUE TITLE
希望可以支持网络不可达使用告警阈值中的自定义通知模版

### ISSUE THREAD

**Issue by doudoui** [apache/hertzbeat#145]
现在ping检测中超时的告警内容为【监控紧急可达性告警: UN_REACHABLE】
![image](https://user-images.githubusercontent.com/46309108/169773404-47c3b80f-c946-4432-9901-bd6ce374615d.png)

希望在告警阈值中的编辑阈值里对超时不可达的状态进行选择，这样就可以使用自定义的通知模版了

**Comment by tomsun28** [comment]
supported
