### ISSUE TITLE
[BUG] The overflow of integers causes the failure of alarm convergence

### ISSUE THREAD

**Issue by MushroomBear** [apache/hertzbeat#1527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

org.dromara.hertzbeat.alert.reduce.AlarmConvergeReduce#filterConverge
```
if (match) {
    long evalInterval = alertConverge.getEvalInterval() * 1000;
    long now = System.currentTimeMillis();
    if (evalInterval <= 0) {
        return true;
    }
    ......
}
```
The type of integer multiplied by integer is integer. When alertConverge.getEvalInterval() is set to the maximum value of integer, overflow will occur after multiplying by 1000, and the result will be 0, which leads to the condition if (evalInterval <= 0) becoming true, and cannot perform alarm convergence.

### Expected Behavior

```
if (match) {
    long evalInterval = alertConverge.getEvalInterval() * 1000L;
    long now = System.currentTimeMillis();
    if (evalInterval <= 0) {
        return true;
    }
    ......
}
```
The type of  alertConverge.getEvalInterval() * 1000L is long，will not  overflow.

### Steps To Reproduce

None

### Environment

```markdown
v1.4.4
```

### Debug logs

None

### Anything else?

None

**Comment by MushroomBear** [comment]
long evalInterval = alertConverge.getEvalInterval() * 1000(L); should be long evalInterval = alertConverge.getEvalInterval() * 1000L；

**Comment by tomsun28** [comment]
hi, 👍👍.  has confirmed this. Can you help us to fix it? 
I think we can limit the max evalInterval or fix the overflow of the integer

**Comment by Calvin979** [comment]
I‘d like to help!

**Comment by tomsun28** [comment]
done
