### ISSUE TITLE
[BUG]The indicator item whose parseType is multiRow does not consider the "response data column name", resulting in missing data and confusing display.

### ISSUE THREAD

**Issue by chengxinkaicxk** [apache/hertzbeat#1548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

以Centos Linux中的Top10 CPU 进程为例：

在实时数据详情时缺失数据：

输入图片说明

在历史图表详情中显示错乱：
![image](https://github.com/dromara/hertzbeat/assets/37535253/b5187ad2-4068-40cf-8635-ef53e360be20)

在服务器上执行命令获取到的结果如下：
![image](https://github.com/dromara/hertzbeat/assets/37535253/86c87016-8ccb-4cdb-9e99-ff0f14d8c15e)

图表详情中的展示结果如下：
![image](https://github.com/dromara/hertzbeat/assets/37535253/0126e1d4-51d0-4e21-bcb4-7a5787a8c459)

如图所示，进程10912的cpu占有率为1.3%，在历史图表详情中cpu占有率为1.3%的没有pid，且pid为10912的cpu占有率结果为0.4%（0.4%其实对应的pid为24336）。目前只测试了centos linux，包括但不限于"Top10 CPU 进程/CPU占有率"、"Top10 CPU 进程/内存占有率"、"Top10 内存进程/内存占有率" 、"Top10 内存进程/CPU占有率"等。

部署方式使用docker进行部署，镜像为最新的，于2024-02-18发现该问题
![image](https://github.com/dromara/hertzbeat/assets/37535253/e3cc4c56-ff18-4475-9663-2bca10de3295)

### Environment

```markdown
HertzBeat version(s):  HertzBeat v1.5.0
```

**Comment by tomsun28** [comment]
thanks for feedback, we will try to reproduce.

**Comment by zqr10159** [comment]
fixed
