### ISSUE TITLE
[Question] [Collection Cluster] page, whether it is possible to add two columns of "Collector Version" and "Collector IP Address"

### ISSUE THREAD

**Issue by leim** [apache/hertzbeat#1549]
### Question

随着部署的采集器越来越多，更新版本时，希望能够直观的看到哪些采集器已经升级，哪些采集器尚未升级。
建议页面增加“采集器版本”和“采集器互联网出口IP地址”两列。

![z00](https://github.com/dromara/hertzbeat/assets/1665397/06dbec68-de8a-4fa3-bd91-501c707eb190)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

As more and more collectors are deployed, when updating the version, we hope to be able to intuitively see which collectors have been upgraded and which collectors have not yet been upgraded.
It is recommended to add "Collector Version" and "Collector Internet Exit IP Address" columns to the page.

![z00](https://github.com/dromara/hertzbeat/assets/1665397/06dbec68-de8a-4fa3-bd91-501c707eb190)

**Comment by Calvin979** [comment]
I'd like to help!
