### ISSUE TITLE
hertzbeat-mysql-victoria-metrics deployment, data storage duration issue

### ISSUE THREAD

**Issue by JiangFFFF** [apache/hertzbeat#1550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. 使用hertzbeat-mysql-victoria-metrics部署 数据时长是默认保存24小时吗，该如何修改呢？
2. 使用图表查询近一天可以正常看到数据，但是查询近1月、近3月都是显示的近6小时的
![image](https://github.com/dromara/hertzbeat/assets/47769347/b5439cb1-f654-4d82-9f57-7f970bd2b978)
![image](https://github.com/dromara/hertzbeat/assets/47769347/47812d30-1dde-40b1-9771-f417d3ebf960)

3.同时监控状态页面也只显示了当天的状态情况 ，但已经跑了10天左右
![image](https://github.com/dromara/hertzbeat/assets/47769347/b3dee504-d1a0-4fe0-96e8-8ef93b6deda7)

### Environment

```markdown
HertzBeat version(s):1.5.0
```

**Comment by tomsun28** [comment]
thanks for feedback.

**Comment by tomsun28** [comment]
fixed
