### ISSUE TITLE
[BUG] <title>[BUG]<title>After the online product Docker was restarted, the running status of the HertzBeat collection cluster was still displayed as offline and did not recover in time .

### ISSUE THREAD

**Issue by QiangQiangshiyanshi** [apache/hertzbeat#1637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![下载](https://github.com/dromara/hertzbeat/assets/76142152/b2570eae-d349-4d65-a3b7-5915cc61bf19)

### Expected Behavior

After dockers is successfully restarted, the HertzBeat collector needs to be back online

### Environment

```markdown
HertzBeat version(s):
```

### Debug logs

1.  Client logs

Docker logs 
- 2024-03-13 09:48:34 [netty-client-worker-1] INFO  org.dromara.hertzbeat.collector.dispatch.entrance.processor.HeartbeatProcessor - collector receive manager server response heartbeat, time: 1710294514815. 

2. 
![下载 (1)](https://github.com/dromara/hertzbeat/assets/76142152/cbf53664-3d9f-4530-b051-0c5a5ae75630)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
👍Got, we will fix it.

**Comment by Nctllnty** [comment]
Is this a known bug?

**Comment by tomsun28** [comment]
> Is this a known bug?

yes, i thinks it is a bug.

**Comment by Calvin979** [comment]
I would like to try

**Comment by tomsun28** [comment]
hi this bug we have fixed.
