### ISSUE TITLE
在自定义监控希望可以添加按时间告警的功能

### ISSUE THREAD

**Issue by ivanmissu** [apache/hertzbeat#166]
首先感谢开源项目，让之前都是零碎的脚本转化为平台去管理监控。

这里希望能添加个可以根据时间告警，比如公司内部有些微信公众号或者云服务器的到期提醒，这些提醒可能都是提醒到手机号或者邮箱，甚至有些人员离职导致账户没有及时更新导致提醒不到实际运营人这里，所以这里希望可以添加一个类似逾期告警的一个功能，可以通过告警平台配置 然后发送钉钉或微信通知。  目前的自定义监控还是需要http请求触发的，这里的到期告警其实不需要请求，只是需要个到期时间。

**Comment by tomsun28** [comment]
hi 谢谢肯定 你描述的功能大致意思是说 支持到期时间这个指标，然后用户可以对其设置阈值，触发到期时间后就发告警是么

**Comment by ivanmissu** [comment]
> hi 谢谢肯定 你描述的功能大致意思是说 支持到期时间这个指标，然后用户可以对其设置阈值，触发到期时间后就发告警是么

是的  就是类似逾期或者临期的一个告警
