### ISSUE TITLE
[Task] WeWorkApp message  is sent in groups<title>

### ISSUE THREAD

**Issue by yangshuDBA** [apache/hertzbeat#1665]
### Description

now WeWorkApp can only send  to ALL , However, most scenarios need to be pushed to specific people at a fixed point。

### Task List

The WeWorkApp now supports all pushes, and cannot be specified to push to the specified person.
Task 1: Add new types of tags, such as asset tags and alarm push tags.
Task 2: Add a specific tag for the message notification to push the specified person.

企微应用现在支持全部推送，无法指定推送给指定的人。
任务一：标签新增类型，如资产标签，告警推送标签。
任务二：消息通知新增推送指定标签，实现推送指定人员。

**Comment by ZY945** [comment]
> ### Description
> now WeWorkApp can only send to ALL , However, most scenarios need to be pushed to specific people at a fixed point。
> 
> ### Task List
> The WeWorkApp now supports all pushes, and cannot be specified to push to the specified person. Task 1: Add new types of tags, such as asset tags and alarm push tags. Task 2: Add a specific tag for the message notification to push the specified person.
> 
> 企微应用现在支持全部推送，无法指定推送给指定的人。 任务一：标签新增类型，如资产标签，告警推送标签。 任务二：消息通知新增推送指定标签，实现推送指定人员。

Can you provide a case study?

**Comment by yangshuDBA** [comment]
> > ### Description
> > now WeWorkApp can only send to ALL , However, most scenarios need to be pushed to specific people at a fixed point。
> > ### Task List
> > The WeWorkApp now supports all pushes, and cannot be specified to push to the specified person. Task 1: Add new types of tags, such as asset tags and alarm push tags. Task 2: Add a specific tag for the message notification to push the specified person.
> > 企微应用现在支持全部推送，无法指定推送给指定的人。 任务一：标签新增类型，如资产标签，告警推送标签。 任务二：消息通知新增推送指定标签，实现推送指定人员。
> 
> Can you provide a case study?
For example, there are three servers hosting 1, 2, and 3, and there are three administrators, users A, B, and C.
Host 1 alarms are pushed to user A, 
host 2 alarms are pushed to users A and B, 
and host 3 alarms are pushed to A, B, and C, like this。
Refer： https://developer.work.weixin.qq.com/document/path/90236   
{
   "touser" : "UserID1|UserID2|UserID3",
   "toparty" : "PartyID1|PartyID2",
   "totag" : "TagID1 | TagID2",
   "msgtype" : "text",
   "agentid" : 1,
   "text" : {
       "content" : "你的快递已到，请携带工卡前往邮件中心领取。\n出发前可查看<a href=\"http://work.weixin.qq.com\">邮件中心视频实况</a>，聪明避开排队。"
   },
   "safe":0,
   "enable_id_trans": 0,
   "enable_duplicate_check": 0,
   "duplicate_check_interval": 1800
}
