### ISSUE TITLE
[BUG] <title>Use rocketMQ to monitor, test links, and report errors on the console

### ISSUE THREAD

**Issue by bayazhao** [apache/hertzbeat#1669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用rocketMQ监控，测试链接，控制台报错
![ff9699348bb23ec57cace40edbbaaa1e_720](https://github.com/dromara/hertzbeat/assets/142704590/ecad5ef7-ec8f-4906-a117-e972c0dd707f)

### Environment

```markdown
HertzBeat version(s):1.4.3
```

**Comment by tomsun28** [comment]
hi, try the latest master code.

**Comment by bayazhao** [comment]
好的

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
OK

**Comment by Ceilzcx** [comment]
hi，is this issues solved? if not, please offer rocketmq version

**Comment by bayazhao** [comment]
你好这个，修改完成的结果能给我写一下具体是那天提交的代码吗
