### ISSUE TITLE
[BUG] <snmp test BUG>

### ISSUE THREAD

**Issue by yky1984** [apache/hertzbeat#1670]
### Current Behavior

WINDOWS主机 snmp测试有个BUG， 当SNMP没设置的时候点了测试，会提示超时，然后配置好SNMP后，再点测试也还是提示超时，要后台重启hertzBeat服务后才会提示测试成功

### Expected Behavior

当可用的时候直接测试提示成功，不需要重启服务后再测试

### Steps To Reproduce

在SNMPV1 V2版本下，添加WINDOWS主机，在主机没配置SNMP的情况下，在添加WINDOWS主机里点测试，提示超时，这属于正常现象，然后在主机里添加SNMP允许的信息，再添加主机点测试的时候仍然提示超时，但是重启3个服务后再点击SNMP测试，才会提示成功。

### Environment

```markdown
HertzBeat version(s): v1.5.0
```

**Comment by TJxiaobao** [comment]
After receiving your feedback, we will fix it as soon as possible. Thank you for your feedback.

**Comment by ZY945** [comment]
> 重启3个服务

What does restarting three services mean?
