### ISSUE TITLE
[BUG] <title>Error when starting service after packaging and compilation

### ISSUE THREAD

**Issue by cainwang0208** [apache/hertzbeat#1685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[新建 Microsoft Word 文档.docx](https://github.com/dromara/hertzbeat/files/14740520/Microsoft.Word.docx)

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
hi, the word is null 0KB, please describe your content in issue.

**Comment by cainwang0208** [comment]
就是镜像拉下来使用的jdk是11，但是代码使用的是17，重新打包后的源码放进去提示版本问题，后面我想通过升级容器中的jdk,然后更改tar包的名字，替换原有的tar包，替换过程中提示tar包正在运行，所以无法进行升级

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The jdk used when pulling down the image is 11, but the code uses 17. When the repackaged source code is put in, it prompts a version problem. Later, I want to upgrade the jdk in the container, and then change the name of the tar package to replace the original tar. package, during the replacement process, it is prompted that the tar package is running, so the upgrade cannot be performed.

**Comment by cainwang0208** [comment]
已解决 要映射两个包   tar包和lib的那个文件夹里面的

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Solved: To map two packages in the folder of tar package and lib
