### ISSUE TITLE
[Task] <support redfish protocol to monitoring server>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1695]
### Description

support redfish protocol to monitoring server.  

Redfish defines a way to interact with computer hardware using a common language, similar to how web browsers communicate with websites. This makes it easier for different software tools and applications to manage servers, storage, networking equipment, and other components  regardless of the manufacturer.

Redfish is  RESTful API. 

refer https://redfish.dmtf.org/ 

mock test server. https://redfish.dmtf.org/redfish/v1 

### Task List

- [ ] design redfish protocol 
- [ ] support redfish protocol to monitoring server.
- [ ] test

**Comment by gjjjj0101** [comment]
I would like to help! Assign it to me please?

**Comment by tomsun28** [comment]
welcome👍
