### ISSUE TITLE
Unorganized Navbar 

### ISSUE THREAD

**Issue by Apurv428** [apache/hertzbeat#172]
**Is your feature request related to a problem? Please describe.**
The buttons on the Navbar are unorganised and are randomly oriented. 
On hovering over the login button, the text of the button gets camouflagued with the background.
![Screenshot (1655)](https://user-images.githubusercontent.com/84929607/171812704-0fc4b9a9-9f64-48e1-b3d0-aa012e72261c.png)

**Describe the solution you'd like**
A clean and organised navbar buttons.
Changing color of the text of the login button after hovering.

**Comment by tomsun28** [comment]
👍👍thanks for this issue, we will fix it later
