### ISSUE TITLE
[Task] <Notification policy acceptance object supports multiple selection>

### ISSUE THREAD

**Issue by shenleg** [apache/hertzbeat#1728]
### Description

我想一个策略发送多个对象，接受对象只能单选。发送多个对象需要创建多个相同的策略，操作是繁琐重复不必要的。希望增加多选操作。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Description

I want a strategy to send multiple objects, and the objects that can be received can only be single-selected. Sending multiple objects requires creating multiple identical policies, and the operation is cumbersome and unnecessary. Hope to add multi-select operation.

### Task List

_No response_
