### ISSUE TITLE
[BUG] When clicking the offline and online collector button, the pop-up window is abnormal.

### ISSUE THREAD

**Issue by cttq-iot** [apache/hertzbeat#1733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

master分支：
![5b858cb18620ab766e5ee6413f61d94](https://github.com/dromara/hertzbeat/assets/111329082/004e3bba-46c7-4ef3-8b03-86196f554d04)
查看代码是前端调用这两个接口的时候多了个/
![image](https://github.com/dromara/hertzbeat/assets/111329082/8c82ecf2-33f4-4176-8d96-5b503b2f4841)
移除这两个下划线接口成功调用

### Environment

```markdown
HertzBeat version(s): master
```

### Debug logs

![5b858cb18620ab766e5ee6413f61d94](https://github.com/dromara/hertzbeat/assets/111329082/004e3bba-46c7-4ef3-8b03-86196f554d04)

**Comment by tomsun28** [comment]
hi, can you submit a pr to fix it?
