### ISSUE TITLE
[Task] <remove the unlicense dependency `wolfy87-eventemitter` in frontend web-app>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1739]
### Description

The web-app dependency `wolfy87-eventemitter` is unlicense, we can not use it. 

This task requires finding which component third parties depend on it and remove the unlicense dependency `wolfy87-eventemitter` in frontend web-app.

 https://npmjs.com/package/wolfy87-eventemitter/v/5.2.9 5.2.9 Unlicense

### Task List

- [ ] find and remove the unlicense dependency `wolfy87-eventemitter` in frontend web-app
- [ ] update the frontend license https://github.com/apache/hertzbeat/blob/master/material/licenses/frontend/LICENSE#L381

**Comment by alpha951** [comment]
Could you please assign this issue to me ?

**Comment by tomsun28** [comment]
@alpha951 hi welcome, has assigned to you. Btw, i think we can remove the unused package `@delon/chart` in web-app to solve this, due the the package depend the `wolfy87-eventemitter`.

**Comment by alpha951** [comment]
Hey @tomsun28 , I've raised a PR #1745 addressing this issue. Let me know if anything is need to be updated.
