### ISSUE TITLE
[Question] Official Website SSL certificate error

### ISSUE THREAD

**Issue by leim** [apache/hertzbeat#1750]
### Question

![z03](https://github.com/apache/hertzbeat/assets/1665397/ceb72dc8-b98e-40c0-be9e-099666df0492)

**Comment by tomsun28** [comment]
hi use the https://hertzbeat.apache.org/ , we will forward the hertzbeat.com to hertzbeat.apache.org

**Comment by tomsun28** [comment]
fix done
