### ISSUE TITLE
[Task] <Add apache incubutor footer page in website>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1752]
### Description

- Add apache incubutor footer page in hertzbeat website footer https://hertzbeat.apache.org/

refer https://streampark.apache.org/ 

<img width="1693" alt="image" src="https://github.com/apache/hertzbeat/assets/24788200/1b7d81a5-3388-4912-bf44-14ad74de6e06">
 

### Task List

- [ ] Add apache incubutor footer page in website

**Comment by sheepbox8646** [comment]
I'll have a try
