### ISSUE TITLE
[Task] <support auto load mysql oracle jar from extern path>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1777]
### Description

now we remove the mysql oracle dependency due license not compatible.  
the task is to support auto load mysql oracle jar from extern path.

When user want to monitoring mysql or oracle, them can download and move the jar to  `/extern-jar`

system load jar from extern path `/extern-jar/*`

`ojdbc8-21.5.0.0.jar`  `orai18n-21.5.0.0`  `mysql-connector-java-8.0.30.jar`

**Comment by zqr10159** [comment]
https://github.com/apache/doris/pull/15346/files
