### ISSUE TITLE
[Task] <update checkstyle config, the file header cannot contain author date>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1781]
### Description

update checkstyle config, limit the java file header cannot contain `@author @date`

https://github.com/apache/hertzbeat/blob/master/script/checkstyle/checkstyle.xml

**Comment by YxYL6125** [comment]
Hello, I want to participate in, plz assigne to me

**Comment by tomsun28** [comment]
> Hello, I want to participate in, plz assigne to me

welcome, has assigned to you

**Comment by MananPoojara** [comment]
i claim update checkstyle config, the file header cannot contain author date

**Comment by YxYL6125** [comment]
It sames like MananPoojara has down :sweat_drops:

**Comment by zqr10159** [comment]
> It sames like MananPoojara has down 💦

Not yet. You can submit it.

**Comment by YxYL6125** [comment]
> > It sames like MananPoojara has down 💦
> 
> 
> 
> Not yet. You can submit it.

down
