### ISSUE TITLE
classes that contain only properties and no methods should use the record type instead

### ISSUE THREAD

**Issue by xuziyang** [apache/hertzbeat#1785]
### Description

Java records offer a more concise and readable syntax compared to traditional Java classes. The streamlined syntax of records allows us to define our data fields and their types in a compact and visually appealing way, making it easier to understand and maintain our code.

**Comment by YxYL6125** [comment]
I would like to try, plz assign to me

**Comment by YxYL6125** [comment]
> ### Description
> Java records offer a more concise and readable syntax compared to traditional Java classes. The streamlined syntax of records allows us to define our data fields and their types in a compact and visually appealing way, making it easier to understand and maintain our code.
> 
> ### Task List
> _No response_

You can organize the Task List so that we can do it in batches.
Or I'll do it later
