### ISSUE TITLE
[BUG] <Failed to run web-app>

### ISSUE THREAD

**Issue by Calvin979** [apache/hertzbeat#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Failed to run web-app while following 
https://github.com/apache/hertzbeat/blob/master/CONTRIBUTING.md#getting-hertzbeat-up-and-running

![image](https://github.com/apache/hertzbeat/assets/131688897/ba8a007d-fb03-4ebe-b5c3-b0ca608f10dc)
![image](https://github.com/apache/hertzbeat/assets/131688897/0e309b7a-64cf-4866-9567-3d7c55bd6d5b)

### Environment

```markdown
HertzBeat version(s):1.5.0
```

**Comment by ZY945** [comment]
Hello, can the backend service be used normally

**Comment by Calvin979** [comment]
Hi, @ZY945 @TJxiaobao 
Backend is running normally.
![image](https://github.com/apache/hertzbeat/assets/131688897/adbfd10b-7820-429a-944f-5c2ac70d637c)

But I found error log says 'APPLICATION FAILED TO START', and it looks like Spring cycle reference causes this problem.(Because I modify backend code)
![image](https://github.com/apache/hertzbeat/assets/131688897/c0d0898e-bfe3-4e9e-8f5c-68dc2eca82a2)

Maybe we should consider do not let backend start successfully if cycle reference happend

**Comment by ZY945** [comment]
> Hi, @ZY945 @TJxiaobao Backend is running normally. ![image](https://private-user-images.githubusercontent.com/131688897/324038148-adbfd10b-7820-429a-944f-5c2ac70d637c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDU0NjIsIm5iZiI6MTcxMzU0NTE2MiwicGF0aCI6Ii8xMzE2ODg4OTcvMzI0MDM4MTQ4LWFkYmZkMTBiLTc4MjAtNDI5YS05NDRmLTVjMmFjNzBkNjM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxNjQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGFhMjc1NGRmYThhMDQ5MjA5YTE3YzdmMDk4MmZlNTdiN2E2NWE0MDNiYmZjZmM2OWUxMWY5YzY1ZGQ1ZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qjA0CHcaa9eMZuMizkHsZqbkipgNLqWpeIh7hQQK5U4)
> 
> But I found error log says 'APPLICATION FAILED TO START', and it looks like Spring cycle reference causes this problem.(Because I've modified backend code) ![image](https://private-user-images.githubusercontent.com/131688897/324038855-c0d0898e-bfe3-4e9e-8f5c-68dc2eca82a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDU0NjIsIm5iZiI6MTcxMzU0NTE2MiwicGF0aCI6Ii8xMzE2ODg4OTcvMzI0MDM4ODU1LWMwZDA4OThlLWJmZTMtNGU5ZS04ZjVjLTY4ZGMyZWNhODJhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxNjQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDZhYWM0MDE3ZmNjZDdkZTJhZDc2ZTRhZGE5MTJhYTAyZDc3NzdmMTlhYjc5MWZmZTQwZjc0Zjk2NzMxYmI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FAbueHNd6-g-eEFwaxuydMfCzRCDB-dWsR2WuzQaeiw)
> 
> Maybe we should consider do not let backend start successfully if cycle reference happend

It seems to be caused by circular dependency.
1. You can try using @ DependsOn or @ Lazy to change the loading order.
Springboot can be set to allow circular references.
I hope it can help you.

**Comment by Calvin979** [comment]
@ZY945 Thanks, I've solved this problem
