### ISSUE TITLE
[Question] Support querying via prometheus for rocketMQ

### ISSUE THREAD

**Issue by Alanxtl** [apache/hertzbeat#1810]
### Question

According to [the doc](https://rocketmq.apache.org/docs/observability/01metrics/), rocketMQ is supported for querying metrics using the Prometheus protocol. Currently the code seems to use the method of creating an instance to query information (https://github.com/apache/hertzbeat/pull/1046), so the metrics that could be queried seems limited and its a waste of connection resource. I think it is necessary to support querying via prometheus for rocketMQ.

btw, I'm not sure if I should create a [Task], so I just create a [Question].

**Comment by tomsun28** [comment]
@Ceilzcx how about this, suggest use Prometheus protocol to query the rocketMQ metrics too.

**Comment by Alanxtl** [comment]
According to the [comment](https://github.com/apache/rocketmq/issues/5615#issuecomment-1331634113) and [RIP-46](https://github.com/apache/rocketmq/wiki/RIP-46-Observability-improvement-for-RocketMQ), they introduced new metrics in the .

[RIP-46](https://github.com/apache/rocketmq/wiki/RIP-46-Observability-improvement-for-RocketMQ), also mentioned that 
> using mqadmin tools, which puts additional pressure on broker and client.

However, the rocketMQ community seems working on

**Comment by Alanxtl** [comment]
> > @Ceilzcx, according to [apache/rocketmq#5615 (comment)](https://github.com/apache/rocketmq/issues/5615#issuecomment-1331634113) and [RIP-46](https://github.com/apache/rocketmq/wiki/RIP-46-Observability-improvement-for-RocketMQ#are-there-any-problems-with-our-current-project), they have introduced new metrics in Prometheus way. See [doc](https://rocketmq.apache.org/docs/observability/01metrics/) for detailed metrics.
> > Besides, [RIP-46](https://github.com/apache/rocketmq/wiki/RIP-46-Observability-improvement-for-RocketMQ), also mentioned that
> > > using mqadmin tools, which puts additional pressure on broker and client.
> 
> good idea. Need to be compatible with old logic？

I do not think it is necessary, the new method covers the metrics of the old one can query after all.
