### ISSUE TITLE
[Task] Historical data storage supports Apache Hbase

### ISSUE THREAD

**Issue by zhangshenghang** [apache/hertzbeat#1836]
### Description

Historical data storage currently supports iotdb, influxdb, etc. Do you need Apache Hbase storage that supports the big data system? If support is needed, I can complete it.
Hbase is a columnar storage. I think it is needed in many scenarios.

**Comment by tomsun28** [comment]
hi our plan is to use victoriametrics for main maintenance later to provide more query capabilities. Nowadays, too many database storages are supported, resulting in limited maintenance efforts and each cannot be the best. Sometimes users are given too many choices and they don’t know how to choose. Convention over configuration, we hope to choose a storage and do it best

**Comment by zhangshenghang** [comment]
Okay, understand😋
