### ISSUE TITLE
[BUG] Debian system Top10 monitoring error

### ISSUE THREAD

**Issue by zhangshenghang** [apache/hertzbeat#1845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the Debian system, when statistics for the Top 10 Memory and Top 10 CPU are displayed, the table headers are also shown, as illustrated in the following image.

![image](https://github.com/apache/hertzbeat/assets/29418975/491ed60b-af05-4142-9796-7f9dec1d9fc3)

### Expected Behavior

To remove the table headers and display the statistics as shown in the following image, adjustments need to be made in the Debian system's display settings or the command used to generate the Top 10 Memory and Top 10 CPU statistics.
﻿
<img width="616" alt="image" src="https://github.com/apache/hertzbeat/assets/29418975/23d31cd7-2109-481e-b70e-b97dd0392bf2">

### Environment

```markdown
HertzBeat version(s): v1.5
```

**Comment by TJxiaobao** [comment]
You're right. Can you try to fix it?
