### ISSUE TITLE
[Question] 看到文件介绍V1.5.x支持【推送方式监控】，实际搭建起来不支持

### ISSUE THREAD

**Issue by learncat163** [apache/hertzbeat#1849]
### Question

https://hertzbeat.apache.org/zh-cn/docs/advanced/extend-push 这篇文档介绍了 V1.5.x支持【推送方式监控】，
实际搭建起来不支持，看到当前的版本确实是1.5.0

**Comment by tomsun28** [comment]
hi push is still under development, we will hide this document first, sorry for causing confusion

**Comment by learncat163** [comment]
ok.thanks. wait it
