### ISSUE TITLE
[BUG] Statistical metric matching fails, resulting in data loss

### ISSUE THREAD

**Issue by zhangshenghang** [apache/hertzbeat#1873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Monitoring metic matching failed

Use ElasticSearch as an example：

issue file：MetricsCollect

On line 171, we see the collected data as shown in the picture below
<img width="908" alt="image" src="https://github.com/apache/hertzbeat/assets/29418975/9466b226-d9a8-447e-9cea-e6329b25a2e9">
<img width="916" alt="image" src="https://github.com/apache/hertzbeat/assets/29418975/59bfaf41-726a-4194-be6a-893324bf3b1d">

When debugging to line 172, it was found that several statistical metric were missing.

<img width="865" alt="image" src="https://github.com/apache/hertzbeat/assets/29418975/09b20597-8322-446d-89e8-414a58fb3624">

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
maybe casue by the pr https://github.com/apache/hertzbeat/pull/1859

**Comment by HeartLinked** [comment]
I can try to fix this issue. Please assign it to me.

**Comment by tomsun28** [comment]
> I can try to fix this issue. Please assign it to me.

hi sorry i just have submit the pr to fix it, you can help review this https://github.com/apache/hertzbeat/pull/1884
