### ISSUE TITLE
[BUG] HTTP API did not fill in non mandatory fields, but prompted an error

### ISSUE THREAD

**Issue by zhangshenghang** [apache/hertzbeat#1895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the HTTP API, not filling in the relative path will prompt an error. But relative path is not a mandatory field
![image](https://github.com/apache/hertzbeat/assets/29418975/d7b9afd7-6d15-45b6-9078-28c9ad8b0b8d)

### Environment

```markdown
HertzBeat version(s): current master
```

**Comment by Aias00** [comment]
assign me , pls
