### ISSUE TITLE
[BUG] <customized menu invalid when update monitoring template yml>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After modifying the monitoring template, the previously customized menu becomes invalid.

<img width="684" alt="image" src="https://github.com/apache/hertzbeat/assets/24788200/2851c107-5507-4c6f-9dee-822b7e55efcf">

<img width="1879" alt="image" src="https://github.com/apache/hertzbeat/assets/24788200/083059e3-d53d-4b84-b43e-dc736b8b9079">

### Expected Behavior

customized menu not invalid 

### Environment

```markdown
HertzBeat version(s): master code
```

**Comment by Aias00** [comment]
i can try
