### ISSUE TITLE
"The email scenario, message notification interface failure."

### ISSUE THREAD

**Issue by luoyuLianga** [apache/hertzbeat#1905]
### Question

docker方式安装：
docker run -d -p 1157:1157 -p 1158:1158 --name hertzbeat tancloud/hertzbeat

验证消息通知接口，后出现失败
![image](https://github.com/apache/hertzbeat/assets/155722980/aa651c60-79ec-4a83-9405-fd2603dd5c95)

触发告警测试失败!
[Email Notify Error] Mail server connection failed. Failed messages: jakarta.mail.MessagingException: Could not connect to SMTP host: smtp.qq.com, port: 587; nested exception is: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message

**Comment by tomsun28** [comment]
try config the smtp.qq.com server port 465
