### ISSUE TITLE
[Task] <support monitoring llm openai>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#1916]
### Description

support monitoring llm Usage, Billing, Account etc
First we can support the openai, use the openai token to access openai restful api to get info data.

**Comment by TJxiaobao** [comment]
Is this task something we can accomplish by configuring yml for the http protocol?

**Comment by tomsun28** [comment]
yes, we can custom define monitoring yml by http protocol.

**Comment by TJxiaobao** [comment]
> yes, we can custom define monitoring yml by http protocol.

I want to try it.

**Comment by TJxiaobao** [comment]
Because @zuobiao-zhou   is interested in this and wants to contribute this task, I will assign this task to him.

**Comment by zuobiao-zhou** [comment]
> Because @zuobiao-zhou is interested in this and wants to contribute this task, I will assign this task to him.

Thx!

**Comment by zuobiao-zhou** [comment]
Hi @tomsun28 , now I can monitor the following four metrics. Is this enough?
![image](https://github.com/apache/hertzbeat/assets/61108539/0e0b2dad-500e-4c35-af77-f3b3aed15812)

**Comment by tomsun28** [comment]
👍👍 Hi, if we can only get these basic metrics from openai restful api, we can propose a version pr first.   
It is recommended to implement the metrics i18n.
