### ISSUE TITLE
Can provided more comprehensive default threshold rules doc?

### ISSUE THREAD

**Issue by YareMine** [apache/hertzbeat#1932]
### Question

有没有比较全的阈值规则配置，给导出一份，好让用户参考配置。比如：操作系统cpu、内存、磁盘监控阈值规则；数据库、springboot、jvm的重点指标阈值规则配置等等。

**Comment by zhangshenghang** [comment]
The threshold rule expression is universal, but it will not be explained separately for springboot. I can add documentation that can be assigned to me. @tomsun28
