### ISSUE TITLE
[BUG] <title>page bug

### ISSUE THREAD

**Issue by Yanshuming1** [apache/hertzbeat#1952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For more operations in the threshold rule, click Export Rule. Click x. No response is received
![image](https://github.com/apache/hertzbeat/assets/118667222/665035ea-1fd1-4527-a022-1196654523e1)

### Environment

```markdown
HertzBeat version(latest version):
```

**Comment by Yanshuming1** [comment]
i can fix

**Comment by TJxiaobao** [comment]
> i can fix

👍👍👍
