### ISSUE TITLE
[Task]Fix the problem of no data for springboot3 monitoring

### ISSUE THREAD

**Issue by zqr10159** [apache/hertzbeat#1956]
### Description

![image](https://github.com/apache/hertzbeat/assets/30048352/ec88c1e8-2a5f-4bb1-a0c4-eeaa6aa3e92d)

**Comment by zhangshenghang** [comment]
Is anyone working on a fix? I can try to fix it

**Comment by zqr10159** [comment]
> Is anyone working on a fix? I can try to fix it
👍👍👍

**Comment by zhangshenghang** [comment]
This problem also exists in springboot2, I will fix it together

<img width="1245" alt="image" src="https://github.com/apache/hertzbeat/assets/29418975/8b262626-b305-4e23-bdb8-497745d57657">
