### ISSUE TITLE
kafka监控[Question] <title>

### ISSUE THREAD

**Issue by comdotrain** [apache/hertzbeat#1962]
### Question

就没有一个完整的kafak监控配置文档吗
![image](https://github.com/apache/hertzbeat/assets/49857580/44c7cd22-5d46-47fd-a46c-a348511c69ae)
这个查看步骤点进去就是文档首页，没有看到具体步骤...我这会儿一直监控失败，来个大佬回复下

**Comment by zhangshenghang** [comment]
This is a monitoring document：https://hertzbeat.apache.org/zh-cn/docs/help/kafka/ @comdotrain 
Can it solve your problem?
