### ISSUE TITLE
[Task] Add issue comment action bot

### ISSUE THREAD

**Issue by yuluo-yx** [apache/hertzbeat#1970]
### Description

Create an issue comment action bot, which can be used to add a label to an issue by adding it to an issue comment or assigning it to a task.

- https://github.com/kubernetes-sigs/gateway-api/issues/3041#issuecomment-2088291932
- https://github.com/alibaba/spring-cloud-alibaba/issues/3713#issuecomment-2088405985

### Task List

- [x] Add github action yml.

**Comment by yuluo-yx** [comment]
If it needs to be done, pls assign to me.

**Comment by tomsun28** [comment]
Our pr label auto manage by https://github.com/apache/hertzbeat/blob/master/.github/labeler.yml
I think issue should not use this, the label should be managed by the committers, like good first issue, bug, lock, assign or others

**Comment by yuluo-yx** [comment]
> Our pr label auto manage by https://github.com/apache/hertzbeat/blob/master/.github/labeler.yml I think issue should not use this, the label should be managed by the committers, like good first issue, bug, lock, assign or others

thank your reply, got it. I will closed this issue.
