### ISSUE TITLE
[Task] Support case-insensitive search

### ISSUE THREAD

**Issue by zhangshenghang** [apache/hertzbeat#1990]
### Description

Threshold rules page. Is it possible to support case-insensitive search, because many times we search without knowing the case of the service.

<img width="331" alt="image" src="https://github.com/apache/hertzbeat/assets/29418975/277104a9-84fe-4a37-8ce7-fa46c59fafc0">
<img width="591" alt="image" src="https://github.com/apache/hertzbeat/assets/29418975/8eab5036-3928-4d3f-84d3-036282ac4f69">

**Comment by tomsun28** [comment]
ok, the search implemented by the frontend component. We will implement this later.
