### ISSUE TITLE
[Question] Front-end `eslint-plugin-jsdoc@39.7.5` do not support node version 20.x and higher

### ISSUE THREAD

**Issue by Thespica** [apache/hertzbeat#2002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I built front-end with node 20.x, met error:
```bash
~/hertzbeat/web-app$ yarn install --registry=https://registry.npmmirror.com
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
error eslint-plugin-jsdoc@39.7.5: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.12.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

But the documentation [here](https://hertzbeat.apache.org/zh-cn/docs/community/development#%E5%89%8D%E7%AB%AF%E5%90%AF%E5%8A%A8) and [here](https://github.com/apache/hertzbeat/tree/master/web-app#quickly-start) declared that the only requirement for node version is higher(including) than 18.

### Expected Behavior

Build front-end successfully.

### Steps To Reproduce

node version: v20.12.2

npm version: 10.5.0

yarn version: 1.22.22

### Environment

```markdown
HertzBeat version(s): current(1.5.0 ~ 1.6.0)
```

### Debug logs

```bash
~/hertzbeat/web-app$ yarn install --registry=https://registry.npmmirror.com
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
error eslint-plugin-jsdoc@39.7.5: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.12.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Anything else?

If I am right, I wanna help solving this problem. Here are two solutions:
1. update documentation to add an up-bound 19 node version.
2. update `eslint-plugin-jsdoc` version(personally prefer).

**Comment by Thespica** [comment]
I dealt with this problem by updating [eslint-plugin-jsdoc](https://www.npmjs.com/package/eslint-plugin-jsdoc?activeTab=readme) to 48.2.5.

**Comment by tomsun28** [comment]
> I have dealt with this problem by updating [eslint-plugin-jsdoc](https://www.npmjs.com/package/eslint-plugin-jsdoc?activeTab=readme) to 48.2.5.

👍 hi, i current use node v18.18.0, can you submit a pr to fix this.
