### ISSUE TITLE
[Task] When the document is modified, add CI to verify whether the modification can pass the build

### ISSUE THREAD

**Issue by LiuTianyou** [apache/hertzbeat#2020]
### Description

Sometimes there are some errors in the document project after pulling the code, which prevents it from running through `npm run start`. It is recommended to add CI to verify whether the modification of the document can be built.

**Comment by LiuTianyou** [comment]
If this CI needs to be added, please assign it to me, thank you

**Comment by tomsun28** [comment]
@LiuTianyou hi welcome to add ci for home.
