### ISSUE TITLE
[BUG] <标签值删除后，数据库value不为null，导致告警通知异常>

### ISSUE THREAD

**Issue by Kylin-Guo** [apache/hertzbeat#2023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- 创建Tag并删除值后，数据库字段不为null：

![图片](https://github.com/apache/hertzbeat/assets/131239856/da964175-90e4-4193-b5c4-df2ccf3dd0d9)

- 创建Tag但不填写值，数据库字段为null：

![图片](https://github.com/apache/hertzbeat/assets/131239856/9104b5d9-bfc2-4452-a8dc-30aedc8dea7c)

- 告警策略中绑定的Tag会由 TEST 变为 TEST: ，若不手动添加标签 TEST: ，则无法发出告警通知

![图片](https://github.com/apache/hertzbeat/assets/131239856/2ee3fa84-3b68-4686-a7da-cd8effee3846)

### Environment

```markdown
HertzBeat version(s):v1.5.0
MySQL Version: 8.0.34
```

**Comment by zhangshenghang** [comment]
Is anyone fixing this? Can be assigned to me

**Comment by JavaProgrammerLB** [comment]
> Is anyone fixing this? Can be assigned to me

i am trying to fix this

**Comment by zhangshenghang** [comment]
> > Is anyone fixing this? Can be assigned to me
> 
> i am trying to fix this

👍🏻👍🏻👍🏻
