### ISSUE TITLE
[BUG] Username field too short

### ISSUE THREAD

**Issue by jvinolas** [apache/hertzbeat#2031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Username field is restricted to 20 chars. Not enough for some users, for example when using a proxy gate with long user:host names:

![image](https://github.com/apache/hertzbeat/assets/2132863/33d842c7-a0fd-4b2c-992b-f09823716b7b)

### Expected Behavior

Longer username field restriction for new monitored hosts.

### Steps To Reproduce

1. docker compose
2. default config
3. add new monitored host
4. username field restricted to 20 chars

### Environment

```markdown
HertzBeat version(s): v1.5.0
```

**Comment by zuobiao-zhou** [comment]
I can fix it.
