### ISSUE TITLE
[Question] API business status code parsing problem

### ISSUE THREAD

**Issue by Chandleroo** [apache/hertzbeat#2050]
### Question

**业务状态响应为“0000”和“0003”，解析为了“0”和“3”**
![image](https://github.com/apache/hertzbeat/assets/33657683/69d48634-4c55-47b3-8e77-ef1d644b6b7c)
![image](https://github.com/apache/hertzbeat/assets/33657683/4c8353e2-9782-4623-a1c6-fa5807ecee56)

**Comment by Chandleroo** [comment]
1.5.0版本没有此问题

**Comment by Chandleroo** [comment]
还有企业微信机器人这个通知配置，我理解手机号和userId非必填吧，二者都可以艾特群成员，或者可以不艾特
![image](https://github.com/apache/hertzbeat/assets/33657683/58ef509c-5e97-44ce-9ab9-c09111848d3c)

**Comment by zhangshenghang** [comment]
> 还有企业微信机器人这个通知配置，我理解手机号和userId非必填吧，二者都可以艾特群成员，或者可以不艾特 ![image](https://private-user-images.githubusercontent.com/33657683/335088859-58ef509c-5e97-44ce-9ab9-c09111848d3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTUzMDIsIm5iZiI6MTcxNzA1NTAwMiwicGF0aCI6Ii8zMzY1NzY4My8zMzUwODg4NTktNThlZjUwOWMtNWU5Ny00NGNlLTlhYjktYzA5MTExODQ4ZDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA3NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YmM2YjRiMmMxNWQ5N2NjNWQwY2FiZmRmNmUzY2FmODc3ZjExMGRhYjM5OTUyMTc3MmRlNDYzYjM2YzA3MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e1Iogch9IkF5RACpwQ9aP5b5fji-jSGWQ3iDrrd1JwI)

I will fix this problem because I have already done it on DingTalk notifications.
You can open two issues, as these are two different problems.

**Comment by Chandleroo** [comment]
> > 还有企业微信机器人这个通知配置，我理解手机号和userId非必填吧，二者都可以艾特群成员，或者可以不艾特 ![image](https://private-user-images.githubusercontent.com/33657683/335088859-58ef509c-5e97-44ce-9ab9-c09111848d3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTUzMDIsIm5iZiI6MTcxNzA1NTAwMiwicGF0aCI6Ii8zMzY1NzY4My8zMzUwODg4NTktNThlZjUwOWMtNWU5Ny00NGNlLTlhYjktYzA5MTExODQ4ZDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA3NDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YmM2YjRiMmMxNWQ5N2NjNWQwY2FiZmRmNmUzY2FmODc3ZjExMGRhYjM5OTUyMTc3MmRlNDYzYjM2YzA3MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e1Iogch9IkF5RACpwQ9aP5b5fji-jSGWQ3iDrrd1JwI)
> 
> I will fix this problem because I have already done it on DingTalk notifications. You can open two issues, as these are two different problems.

好的，谢谢

**Comment by Chandleroo** [comment]
> @Chandleroo hi if you want the `status` result is 0000, you can custom the metrics type is string not number. It is not a bug.

我确认了一下配置，就是设置的number

**Comment by zhangshenghang** [comment]
> > @Chandleroo hi if you want the `status` result is 0000, you can custom the metrics type is string not number. It is not a bug.
> 
> 我确认了一下配置，就是设置的string，不是number

Hi , I am trying to fix this issue , Please wait a few days
