### ISSUE TITLE
Can add an automatic refresh to the monitoring list?

### ISSUE THREAD

**Issue by ShineDevelopment** [apache/hertzbeat#2053]
### Description

任务状态 需要手动刷新才会变

**Comment by zuobiao-zhou** [comment]
I want to have a try.

**Comment by tomsun28** [comment]
hi, welcome. btw, what the refresh time is if we config, suggest not too short

**Comment by ShineDevelopment** [comment]
> 嗨，欢迎。顺便问一下，如果我们配置刷新时间，建议不要太短

可以根据添加监控时的监控周期那个时间进行刷新吗？

**Comment by zuobiao-zhou** [comment]
> hi, welcome. btw, what the refresh time is if we config, suggest not too short

Hello, I have some ideas:

1. When a user creates a new monitor, its actual status should be displayed directly in the monitoring center. Currently, even if the monitor is unavailable, its status will only be updated after a monitoring cycle has passed.

2. Users likely want to quickly know about changes in the status of a monitor. However, configuring a refresh time for each monitor individually is obviously impractical. If we set the automatic refresh time for all monitor statuses to be close to the most common monitoring cycle, such as 2 minutes, this seems a bit short. What negative impacts might this have?

**Comment by tomsun28** [comment]
hi, we can auto refresh for current this pageable monitors as you see, 2 minutes cycle time is good. There is might not negative impact.

**Comment by gjjjj0101** [comment]
hi, I have some thoughts on your ideas：If we want to get the actual status immediately, we may need to send a one-time monitoring task to the collector, so that it can immediately return the results and display them to the user. However, this may cause a problem that if the user frequently refreshes immediately, many one-time collection tasks will  be generated, causing or increasing the pressure on the collected service.

> > hi, welcome. btw, what the refresh time is if we config, suggest not too short
> 
> Hello, I have some ideas:
> 
> 1. When a user creates a new monitor, its actual status should be displayed directly in the monitoring center. Currently, even if the monitor is unavailable, its status will only be updated after a monitoring cycle has passed.
> 2. Users likely want to quickly know about changes in the status of a monitor. However, configuring a refresh time for each monitor individually is obviously impractical. If we set the automatic refresh time for all monitor statuses to be close to the most common monitoring cycle, such as 2 minutes, this seems a bit short. What negative impacts might this have?

**Comment by zuobiao-zhou** [comment]
> hi, I have some thoughts on your ideas：If we want to get the actual status immediately, we may need to send a one-time monitoring task to the collector, so that it can immediately return the results and display them to the user. However, this may cause a problem that if the user frequently refreshes immediately, many one-time collection tasks will be generated, causing or increasing the pressure on the collected service.
> 
> > > hi, welcome. btw, what the refresh time is if we config, suggest not too short
> > 
> > 
> > Hello, I have some ideas:
> > 
> > 1. When a user creates a new monitor, its actual status should be displayed directly in the monitoring center. Currently, even if the monitor is unavailable, its status will only be updated after a monitoring cycle has passed.
> > 2. Users likely want to quickly know about changes in the status of a monitor. However, configuring a refresh time for each monitor individually is obviously impractical. If we set the automatic refresh time for all monitor statuses to be close to the most common monitoring cycle, such as 2 minutes, this seems a bit short. What negative impacts might this have?

Sorry for the misunderstanding. What I meant is that when a user creates a new monitor, its actual status should be accurately displayed. Currently, its status is always shown as "Up" regardless of the situation. 

When manually or automatically refreshing the monitor list page, all monitors should simply be read from the database without creating a large number of collect tasks.
