### ISSUE TITLE
[Question] 关于监控历史数据保留时长

### ISSUE THREAD

**Issue by Kylin-Guo** [apache/hertzbeat#2055]
### Question

以下是 VictoriaMetrics 官方关于历史数据保留时长的解释，在不进行 -retentionPeriod 参数设置时，默认保留时长为1个月

![image](https://github.com/apache/hertzbeat/assets/131239856/a9fabee2-d8f8-47a4-bfc4-a296214557d9)

但在 HertzBeat 的 “监控历史图表详情” 中我最多只能够看到最近24小时的历史记录，点击 1周、1个月、3个月等选项虽然会有重新 loading ，但监控图表的内容并没有刷新，请问是我的配置异常还是 HertzBeat 存在 bug？

![image](https://github.com/apache/hertzbeat/assets/131239856/7e0d0c20-ef6b-4aec-b625-51b161e1adcd)

VictoriaMetrics Version：v1.95.1
HertzBeat Version：v1.5.0

**Comment by zqr10159** [comment]
This is a bug in hertzbeat that has been fixed in the upcoming 1.6.0 release
