### ISSUE TITLE
If N monitors are deployed on the same ip address, the task status is abnormal

### ISSUE THREAD

**Issue by ShineDevelopment** [apache/hertzbeat#2062]
### Description

The same ip address service deploys a tcp monitor and an http monitor. And then you stop the service and you look at the monitoring center, the status of the task and there are a couple of things going on here; The first two states are both normal, the second two states one is normal, one is abnormal, and the third is both abnormal (this is correct).

**Comment by ShineDevelopment** [comment]
In addition, alarm convergence is configured

**Comment by Yanshuming1** [comment]
Are there five monitors in there？

**Comment by Yanshuming1** [comment]
i can fix

**Comment by ShineDevelopment** [comment]
> 我可以修复

是配置了告警收敛后才会出现此情况
