### ISSUE TITLE
flink 任务监控指标过少

### ISSUE THREAD

**Issue by Roger0917** [apache/hertzbeat#2069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当前只有slot和任务的指标

### Expected Behavior

期望加上对所有taskmanager和jobmanager的jvm 相关指标的监控，类似于flink web ui那样

### Environment

```markdown
HertzBeat version(s):
```

**Comment by zhangshenghang** [comment]
Do you have a detailed list? I am planning to add monitoring information

**Comment by zhangshenghang** [comment]
Since I also use Flink monitoring, I will first add the details of monitoring in Flink on yarn mode. Flink Cluster mode monitoring will be started after Flink on Yarn is completed.
