### ISSUE TITLE
[Task] <Add and update license documents for newly added third-party dependency packages>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#2081]
### Description

```
        <!-- https://mvnrepository.com/artifact/com.beetstra.jutf7/jutf7 -->
        <dependency>
            <groupId>com.beetstra.jutf7</groupId>
            <artifactId>jutf7</artifactId>
            <version>1.0.0</version>
        </dependency>
```

link pr https://github.com/apache/hertzbeat/pull/2059 

license doc here https://github.com/apache/hertzbeat/tree/master/material/licenses 
We should consider the third-party denpendency and itself dependency packages.

**Comment by Calvin979** [comment]
I would like to help!
