### ISSUE TITLE
[BUG] <api alerts summary response error>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#2085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

api `api/alerts/summary` response data here, `priorityWarningNum` `priorityCriticalNum` `priorityEmergencyNum` is always 0, maybe cause by `jpa ecliseLink replace`
``` 
    "data": {
        "total": 883,
        "dealNum": 883,
        "rate": 100.0,
        "priorityWarningNum": 0,
        "priorityCriticalNum": 0,
        "priorityEmergencyNum": 0
    }
```

### Steps To Reproduce

request: http://localhost:4200/api/alerts/summary

response:

```
{
    "data": {
        "total": 883,
        "dealNum": 883,
        "rate": 100.0,
        "priorityWarningNum": 0,
        "priorityCriticalNum": 0,
        "priorityEmergencyNum": 0
    },
    "msg": null,
    "code": 0
}
```

### Environment

```markdown
HertzBeat version(s): 1.6.0
```

**Comment by Ceilzcx** [comment]
assign to me
