### ISSUE TITLE
[BUG] <alarm notice error>

### ISSUE THREAD

**Issue by zhangnaifu1** [apache/hertzbeat#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在添加通知策略时，配置了通知时间段，无法出发告警功能，清楚通知时间段则正常

### Expected Behavior

无

### Steps To Reproduce

1、添加通知策略
2、配置通知时间段

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

### Debug logs

无

### Anything else?

无

**Comment by Calvin979** [comment]
I would like to help
