### ISSUE TITLE
[BUG] <WeWork robot Receiver, Phone&Useid is required fields>

### ISSUE THREAD

**Issue by Kylin-Guo** [apache/hertzbeat#2103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![图片](https://github.com/apache/hertzbeat/assets/131239856/37a0b210-f85b-42fb-9efc-b08a604a639b)

**目前可以填写任意字符绕过此限制，不填写则无法保存**

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

**Comment by zhangshenghang** [comment]
Hi，Fixed in this PR 
[https://github.com/apache/hertzbeat/pull/2102](https://github.com/apache/hertzbeat/pull/2102)

**Comment by Kylin-Guo** [comment]
Thank you for your contributions.
