### ISSUE TITLE
[BUG] The setting for "Alert Threshold Association with Monitors" is invalid.

### ISSUE THREAD

**Issue by frede2010** [apache/hertzbeat#2105]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

<img width="1088" alt="image" src="https://github.com/apache/hertzbeat/assets/16717330/3b554f95-de78-4ec0-aaac-4dc59d221094">
Move the Marquee_DEV_Mysql from the left side of this interface to the right side, confirm, and then reopen it, but it remains on the left side.

### Steps To Reproduce

1. Mac OS 13.6.6 (22G630). Docker部署，版本 1.6
2. 重现步骤：

https://github.com/apache/hertzbeat/assets/16717330/2ef24e08-d683-4b05-8f0b-72034a1afa8d

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

**Comment by tomsun28** [comment]
Got it. Maybe this cause by the `hibernate -> eclipseLink`

**Comment by Pandas886** [comment]
Please assign it to me.

**Comment by tomsun28** [comment]
fixed
