### ISSUE TITLE
[BUG] The prompt information on the "[Collector Cluster]" page is incorrect.

### ISSUE THREAD

**Issue by kerwin612** [apache/hertzbeat#2113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
HertzBeat version(s): master
```

### Debug logs

![bug](https://github.com/apache/hertzbeat/assets/3371163/a85bac4a-7386-40ee-a6d4-a817e88470c3)

**Comment by zhangshenghang** [comment]
Can be assigned to me, I will fix it

**Comment by LiangliangSui** [comment]
Hello @tomsun28 @kerwin612 , can I do this job? If so, please assign it to me.
