### ISSUE TITLE
[Task] Update the docker startup commands

### ISSUE THREAD

**Issue by zqr10159** [apache/hertzbeat#2146]
### Description

Update the docker startup commands in the documentation to mount the ext-lib directory, and explain the ext-lib directory in more detail in the documentation

**Comment by ShineDevelopment** [comment]
我来

**Comment by zqr10159** [comment]
For english, `home/docs/start/docker-deploy.md` 
For chinese,`home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/docker-deploy.md`
