### ISSUE TITLE
[BUG] <alarm slience not work>

### ISSUE THREAD

**Issue by cdphantom** [apache/hertzbeat#2156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

docker安装V1.6.0版本,时区也设置为TZ=Asia/Shanghai
设置周期性静时间段为每天的00:00-10:00
钉钉还是能收到推送的告警信息
![27da74829c612b302c844c3742ebdcb](https://github.com/apache/hertzbeat/assets/12674795/03394553-9f62-4c50-86a9-94d2676d07fa)
![fbceb90639a1e96de9affc6e244dedd](https://github.com/apache/hertzbeat/assets/12674795/2704802e-70e5-46a9-83de-c5d743a07961)
![77962589b0d0b4922a1a1589ee25ac1](https://github.com/apache/hertzbeat/assets/12674795/d5c2f3df-a856-4aae-9ddc-73e5fc04e08d)
![f4422e7f27a45c39fff011d93d294ac](https://github.com/apache/hertzbeat/assets/12674795/0759de04-ed40-411f-b3a0-3efd30434636)

### Environment

```markdown
HertzBeat version(s):V1.6.0
```

### Anything else?

期望跨天设置
比如从前一天的晚上的10点到第二天早上的8点都支持静默

**Comment by Calvin979** [comment]
It is the same problem with #2097 
Link pr: #2122 
@tomsun28
