### ISSUE TITLE
[Task] Customizable Refresh Intervals for Monitoring Metrics

### ISSUE THREAD

**Issue by yangshuDBA** [apache/hertzbeat#2188]
### Description

The current system only allows setting a unified refresh interval for monitoring assets such as the processor, memory, and hard disk of the host. However, in practice, these metrics often require different refresh intervals; for example, disk monitoring may need to refresh every 60 seconds, while processor monitoring may need to refresh every 10 seconds.

To address this, we propose enhancing the monitoring template to allow custom refresh intervals for individual metrics. If a specific interval is not defined for a metric, it should default to the standard refresh interval set for the asset.
![image](https://github.com/apache/hertzbeat/assets/112070510/695dfdd8-567f-4cca-a47a-a0fa7fd32eca)

Monitor template
![image](https://github.com/apache/hertzbeat/assets/112070510/440541df-629d-44e3-be50-1d875112f8c8)

### Task 2: Support Default Refresh Intervals for Metrics in Monitoring Templates When Not Defined

**Comment by zuobiao-zhou** [comment]
please assign to me.
