### ISSUE TITLE
[Task] Enterprise WeChat application supports custom notifications for user group

### ISSUE THREAD

**Issue by yangshuDBA** [apache/hertzbeat#2195]
### Description

The Enterprise WeChat application currently only supports notifications to all personnel. It is expected to support customized notifications like the Enterprise WeChat robot.

For example, there are three servers host1, 2, and 3, and there are three administrators, users A, B, and C.
Host 1 alarms are pushed to user A,
host 2 alarms are pushed to users A and B,
host 3 alarms are pushed to A, B, and C, like this。
Refer： https://developer.work.weixin.qq.com/document/path/90236
{
"touser" : "UserID1|UserID2|UserID3",
"toparty" : "PartyID1|PartyID2",
"totag" : "TagID1 | TagID2",
"msgtype" : "text",
"agentid" : 1,
"text" : {
"content" : "你的快递已到，请携带工卡前往邮件中心领取。\n出发前可查看<a href="[http://work.weixin.qq.com\">邮件中心视频实况](http://work.weixin.qq.xn--com%5C"%3E-4t2pl9efxo189ay8mus2nwsyaqp5a/)，聪明避开排队。"
},
"safe":0,
"enable_id_trans": 0,
"enable_duplicate_check": 0,
"duplicate_check_interval": 1800
}

--this is We Work Robot
![image](https://github.com/apache/hertzbeat/assets/112070510/eef7911e-ef89-47f4-8ea4-cf50b2ecd10d)

-- Need Enterprise WeChat application
![image](https://github.com/apache/hertzbeat/assets/112070510/5d80bfcc-97d9-437d-ada7-7276286cd84b)

### Task List

Task 1:    Implement front-end web interface adjustment
![image](https://github.com/apache/hertzbeat/assets/112070510/5d80bfcc-97d9-437d-ada7-7276286cd84b)

Task 2： Implement back-end corresponding functions

**Comment by Yanshuming1** [comment]
i can fix
