### ISSUE TITLE
能像zabbix一样用snmp监控网络设备硬件吗？ 

### ISSUE THREAD

**Issue by etanman** [apache/hertzbeat#2208]
### Question

如果只能监控软件，是不是有缺陷？希望能真正代替zabbix。

**Comment by tomsun28** [comment]
hi, it can. See https://hertzbeat.apache.org/docs/advanced/extend-snmp

**Comment by etanman** [comment]
原来可以支持snmp协议，太好了，能不能像zsbbix一样内置一些常用设备的模块，因为对于新手来讲，这是一件很难的事。

**Comment by etanman** [comment]
> hi, it can. See https://hertzbeat.apache.org/docs/advanced/extend-snmp

原来可以支持snmp协议，太好了，能不能像zsbbix一样内置一些常用设备的模块，因为对于新手来讲，这是一件很难的事。

**Comment by tomsun28** [comment]
> 原来可以支持snmp协议，太好了，能不能像zsbbix一样内置一些常用设备的模块，因为对于新手来讲，这是一件很难的事。

可以查看下现有的或者其它朋友网络分享的，这个我们会慢慢新增更多。

**Comment by etanman** [comment]
什么时候能增加对浪潮、深信服、奇安信等国内品牌的网络设备的支持？
