### ISSUE TITLE
[BUG] [Front-end] Monitoring task update time does not refresh

### ISSUE THREAD

**Issue by zuobiao-zhou** [apache/hertzbeat#2240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the data collection task is completed and the data is reported, the update time of the monitoring task does not refresh automatically.

![image](https://github.com/apache/hertzbeat/assets/61108539/bbe649de-995a-4b7f-8d7e-8b4f33ea4e89)

### Expected Behavior

When the collection task is completed and data is reported, the update time of the monitoring task is automatically refreshed.

### Environment

```markdown
HertzBeat version(s):
HertzBeat V1.6.0, master branch
```

**Comment by zqr10159** [comment]
This time is the last time you edited the monitor not the time of collect
