### ISSUE TITLE
[BUG] theme is invalidated after refresh

### ISSUE THREAD

**Issue by rty813** [apache/hertzbeat#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I set the theme to black, but after refreshing the page, it reverts back to white.

### Expected Behavior

It should remain black

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

**Comment by Aias00** [comment]
@yykaue

**Comment by keaifafafa** [comment]
I want to try it.

**Comment by tomsun28** [comment]
> I want to try it.

welcome, has assigned to you.

**Comment by keaifafafa** [comment]
@rty813 Hello, I couldn't reproduce the issue locally.  Could you provide the test steps?  However, in a similar scenario, I encountered a situation like the one you described: I set the theme to black in http://localhost:4200/setting/settings/config, and then navigated to http://localhost:4200/dashboard, but it still showed the original theme.

**Comment by rty813** [comment]
@keaifafafa Indeed, I am unable to replicate the refresh issue as well. If you re-enter the website address, it will indeed display the original theme.
