### ISSUE TITLE
[Question] Can the monitoring cycle be modified in batches? It will be troublesome to modify if there are many servers.

### ISSUE THREAD

**Issue by yangxinpei2015** [apache/hertzbeat#2270]
### Question

监控周期能不能加一个批量修改，服务器数量多的话改起来很麻烦

**Comment by tomsun28** [comment]
maybe you can use the monitors batch import.

**Comment by zqr10159** [comment]
If you have such a need, the current recommendation is to directly execute the update statement to modify the hzb_monitor table
