### ISSUE TITLE
[Question] docker issues of the deployment collector

### ISSUE THREAD

**Issue by Yanshuming1** [apache/hertzbeat#2275]
### Question

<img width="547" alt="image" src="https://github.com/user-attachments/assets/2444dd5d-f305-4b69-989a-fda58f39e463">

problem description：
After I have created a collector, then if I want to create a collector, because - name is conflicting, so executing docker command on a server will conflict error

error：
ysm@Zhuanz ~ % docker run -d \              
    -e IDENTITY=DOCKER_localhost \
    -e MANAGER_HOST=192.168.0.110 \
    -e MODE=public \
    --name hertzbeat-collector apache/hertzbeat-collector
50d3ec0ded6348264c8c7f1a8e1c2fb1adbff572422bdcfd15f01c6b6b1fc9bc
ysm@Zhuanz ~ % docker run -d \
    -e IDENTITY=MYSQL_127.0.0.1 \
    -e MANAGER_HOST=192.168.0.110 \
    -e MODE=public \
    --name hertzbeat-collector apache/hertzbeat-collector
docker: Error response from daemon: Conflict. The container name "/hertzbeat-collector" is already in use by container "50d3ec0ded6348264c8c7f1a8e1c2fb1adbff572422bdcfd15f01c6b6b1fc9bc". You have to remove (or rename) that container to be able to reuse that name.

**Comment by LiuTianyou** [comment]
Hi, this is a limitation of Docker. Each container must have a unique name. So when deploying multiple collectors, you need to modify the value  of  `--name` or remove `--name hertzbeat-collertor`.

**Comment by Yanshuming1** [comment]
> Hi, this is a limitation of Docker. Each container must have a unique name. So when deploying multiple collectors, you need to modify the value of `--name` or remove `--name hertzbeat-collector`.

I was wondering if I could optimize this function to generate a new name for each generated docker instruction if it already exists in hertzbeat's acquisition collector
