### ISSUE TITLE
[BUG] The edit threshold rule modal cannot be cleared

### ISSUE THREAD

**Issue by LiuTianyou** [apache/hertzbeat#2276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After editing any threshold rule, click Add Threshold Rule again, and the edit modal will still display the content just edited.

### Expected Behavior

Each click on the Add Threshold Rule button should display an empty form

### Environment

```markdown
HertzBeat version(s):1.6.0
```

**Comment by Aias00** [comment]
i wanna try, assign me pls

**Comment by Aias00** [comment]
i found this bug may be already handled
