### ISSUE TITLE
[Question] 是否可以支持表字段的监控预警

### ISSUE THREAD

**Issue by dujiecn** [apache/hertzbeat#2283]
### Question

能否细化到具体指标表字段的值进行监控呢？比如说现在有一个天气指标表，里面有一个温度值字段，达到多少进行告警

**Comment by tomsun28** [comment]
hi, same with https://github.com/apache/hertzbeat/issues/2278

**Comment by Yanshuming1** [comment]
Custom yml, then specify protocol: jdbc, in sql to write your query sql, should be able to achieve the functionality you want
