### ISSUE TITLE
[bug] <sometime e2e test work success, sometime failed>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#2293]
### Question

the e2e test code: https://github.com/apache/hertzbeat/tree/master/e2e 

When the code does not involve any changes to e2e, sometimes the e2e test succeeds and sometimes fails, which is very strange.

see action: https://github.com/apache/hertzbeat/actions/workflows/backend-build-test.yml

success: https://github.com/apache/hertzbeat/actions/runs/9957905618 

failed: https://github.com/apache/hertzbeat/actions/runs/9957272366

**Comment by yuluo-yx** [comment]
![image](https://github.com/user-attachments/assets/f2900505-02b5-4ed1-93b6-1c3eb3f0b0e4)

**Comment by yuluo-yx** [comment]
btw, [5618 ](https://github.com/apache/hertzbeat/actions/runs/9957905618 is a failed job, they've reversed the markings. @tomsun28

**Comment by tomsun28** [comment]
> I looked at the failed actions, and most of the http requests were due to 401 errors, and some were due to container exits

hi, yes. not sure if the 401 error is caused by not carrying a access token or something else.

**Comment by yuluo-yx** [comment]
> > I looked at the failed actions, and most of the http requests were due to 401 errors, and some were due to container exits
> 
> hi, yes. not sure if the 401 error is caused by not carrying a access token or something else.

We can keep the running logs inside the container when e2e fails, and then analyze them to get the cause, which requires modifying the e2e test file
