### ISSUE TITLE
[BUG] Unable to specify collector when creating a monitor

### ISSUE THREAD

**Issue by zuobiao-zhou** [apache/hertzbeat#2300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to specify collector when creating a monitor

![image](https://github.com/user-attachments/assets/0ff7bc3c-fcae-440c-9470-ba988c8f6f26)
![image](https://github.com/user-attachments/assets/9c64d501-150f-4546-84fa-5d47fcf4e439)

### Expected Behavior

When the collector is specified, the collector's name can be correctly transmitted.

### Environment

```markdown
HertzBeat version(s): 1.6.0 master
```

**Comment by Calvin979** [comment]
I would like to help
