### ISSUE TITLE
1.6版本oracle数据库连接有问题

### ISSUE THREAD

**Issue by tianyalc1** [apache/hertzbeat#2307]
### Question

我在1.5版本中oracle数据库监控，创建监控连接正常。下载新版本1.6  创建oracle数据库监控，测试无法连接。

**Comment by Kylin-Guo** [comment]
> 由于apache基金会对于license合规的要求，HertzBeat的安装包不能包含mysql，oracle等gpl许可的依赖，需要用户自行添加，用户可通过以下链接自行下载驱动 jar 放到本地 `ext-lib`目录下，然后启动时将`ext-lib`挂载到容器的 `/opt/hertzbeat/ext-lib`目录。

请参考第4点进行驱动下载：
https://hertzbeat.apache.org/zh-cn/blog/2024/06/11/hertzbeat-v1.6.0-update
