### ISSUE TITLE
[Question]store real-time metrics data not support redis-cluster?

### ISSUE THREAD

**Issue by zjh-Github** [apache/hertzbeat#2308]
### Question

![image](https://github.com/user-attachments/assets/a13b58fe-d7c7-466f-be0a-dcd0adbb3cb9)

存储实时数据redis不支持集群吗？

**Comment by Calvin979** [comment]
Yes, redis cluster is not supported now.
Please assign this issue to me. @tomsun28

**Comment by Calvin979** [comment]
@tomsun28 May I use the third dependency like `Jedis` or `Redisson`?

**Comment by Yanshuming1** [comment]
> @tomsun28 May I use the third dependency like `Jedis` or `Redisson`?

From my point of view, the project uses lettuce framework for redis operation，lettuce seems to support cluster as well

**Comment by tomsun28** [comment]
yes, we try to avoid use other third-party packages
