### ISSUE TITLE
[BUG] jpa expired data clean error

### ISSUE THREAD

**Issue by zjh-Github** [apache/hertzbeat#2310]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

delete a half data

### Expected Behavior

truncate table

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

### Debug logs

 
![image](https://github.com/user-attachments/assets/a4405fd6-d305-4460-8e5e-515cb3427f20)

**Comment by pwallk** [comment]
The delNum argument is not passed correctly, and pgsql does not support the update | delete limit syntax
![5629581dc103694470adc6dbf70b0c2](https://github.com/user-attachments/assets/bac845a2-b450-4bad-9f5e-8dafee068910)

**Comment by pwallk** [comment]
When an exception occurs, it will truncate table

**Comment by pwallk** [comment]
I can fix it @tomsun28
