### ISSUE TITLE
[BUG] 添加自定义监控模板报错

### ISSUE THREAD

**Issue by zjh-Github** [apache/hertzbeat#2335]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/fe8faa8a-6bfc-467f-8b02-f8b472cf9977)

docker contianer:
![image](https://github.com/user-attachments/assets/d1870d03-bf71-4516-9f36-0bb8eca853f7)

![image](https://github.com/user-attachments/assets/3ba2a782-8227-4af2-96e8-c857a8fec98b)

新增自定义监控似乎显示有问题？

### Expected Behavior

no error

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

### Debug logs

log:
![image](https://github.com/user-attachments/assets/67d9a4ad-e8e3-4b5b-a4c1-e88f9a71aa42)

**Comment by pwallk** [comment]
Whether the i18n key is not empty and the value is empty. In this case, an exception occurs：
![Clip_2024-07-22_17-09-21](https://github.com/user-attachments/assets/35437706-f166-4a59-b446-789a1bef47cd)

**Comment by Aias00** [comment]
@pwallk r u handling this problem? if u r not doing this, i can try

**Comment by pwallk** [comment]
> 你在处理这个问题吗？如果你不这样做，我可以试试

I am currently dealing with this issue

**Comment by Aias00** [comment]
> > 你在处理这个问题吗？如果你不这样做，我可以试试
> 
> I am currently dealing with this issue

👌 may be add nonull filter can handle that
<img width="631" alt="image" src="https://github.com/user-attachments/assets/4fed95ce-7c6b-441b-b096-7a2c2f406a71">
