### ISSUE TITLE
[EMAIL STARTTLS] <SMTPSendFailedException>

### ISSUE THREAD

**Issue by garrettdo** [apache/hertzbeat#2365]
### Question

**apache/hertzbeat:latest**

`[Email Notify Error] Failed messages: org.eclipse.angus.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [SG2PR02CA0073.apcprd02.prod.outlook.com 2024-07-24T03:43:18.298Z 08DCAB6EB788477A]`

**Comment by Aias00** [comment]
hi, which mail server do u use, and which mail server do u sending to

**Comment by garrettdo** [comment]
> hi, which mail server do u use, and which mail server were u sending to 

office 365

smtp.office365.com
587

**Comment by Aias00** [comment]
so u are sending a mail from office365 to office365 ?  right？

**Comment by Aias00** [comment]
> office365

which is outlook?
