### ISSUE TITLE
[Question] The master branch image cannot be started after creation

### ISSUE THREAD

**Issue by Chandleroo** [apache/hertzbeat#2377]
### Question

当我使用script目录下的Dockerfile制作镜像后，启动容器报异常：exec ./bin/entrypoint.sh: no such file or directory
![image](https://github.com/user-attachments/assets/dad73c62-d75b-4cc9-8716-7f07f395a57e)
![image](https://github.com/user-attachments/assets/b0d32c69-3aa0-4bb9-a791-9246b2d51cdb)

**Comment by yuluo-yx** [comment]
How did you build it? I don't have any problems here

![image](https://github.com/user-attachments/assets/f118c6c6-994e-4392-a3df-e9dcaf6c6849)

maybe you can see: https://hertzbeat.apache.org/zh-cn/docs/start/docker-deploy

**Comment by Chandleroo** [comment]
> How did you build it? I don't have any problems here
> 
> ![image](https://private-user-images.githubusercontent.com/77964041/352043689-f118c6c6-994e-4392-a3df-e9dcaf6c6849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzY2MjksIm5iZiI6MTcyMTk3NjMyOSwicGF0aCI6Ii83Nzk2NDA0MS8zNTIwNDM2ODktZjExOGM2YzYtOTk0ZS00MzkyLWEzZGYtZTlkY2FmNmM2ODQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA2NDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNGI0MjU2ZTM0N2I2OWY5MjQ2OGM1Yzk2NjI0ZTBkNDE2MDk2MzY1YzQ5ZmQ1Y2VhOWI0OGU2ZGFlYzNiMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RuLu-CDVxJKKBvoW1nq0D9R7xo6cHAhCj6wRW2ERFQ)
> 
> maybe you can see: https://hertzbeat.apache.org/zh-cn/docs/start/docker-deploy

谢谢您的回复，我找到问题所在了，当git clone项目到本地Window时，文件换行符成为了CRLF，这个导致了构建镜像的问题，需要修改文件换行符为LF,再次构建没有出现问题

**Comment by yuluo-yx** [comment]
if saved, can closed this issue.
