### ISSUE TITLE
[Question] The master branch code does not work when I specify the collector for the task (rather than the default system scheduling)

### ISSUE THREAD

**Issue by Chandleroo** [apache/hertzbeat#2388]
### Question

![image](https://github.com/user-attachments/assets/4114362d-5715-4aff-8514-64cbdbe3f3d1)
![image](https://github.com/user-attachments/assets/811ac286-fe54-49f7-9894-63b84c0b24f6)

**Comment by Calvin979** [comment]
![image](https://github.com/user-attachments/assets/a083c4e3-b91f-487b-966b-6a9b0809f1a4)
Seems it can't be reproduced.
Update your code and have a try.

**Comment by Chandleroo** [comment]
https://github.com/user-attachments/assets/dfd79ed9-8c51-40e3-8165-cbaf16572113

我这边上传了一个视频，用的就是新代码，直接从master拉去的代码，然后制作的镜像，指定收集器时没有生效，始终是默认系统调度

**Comment by Chandleroo** [comment]
问题解决了，webapp最新代码修复了此问题，谢谢，打扰了
