### ISSUE TITLE
[Question] Urgent need for global or environment variables

### ISSUE THREAD

**Issue by jinghewang** [apache/hertzbeat#2395]
### Question

我的需求是这样，第一步获取 token , 第二步  通过token 访问其它接口（很多不同监控），现在的做法是每个监控都要把 请求token 的操作带着，不是很方便 ，能否有比较方便 的方式 ，如全局变量，环境变量之类 ，或 在一个 监控中获取其它监控的数据 之类的 ，请帮忙解答。

**Comment by tomsun28** [comment]
hi maybe you can refer this https://hertzbeat.apache.org/docs/advanced/extend-http-example-token

**Comment by jinghewang** [comment]
我已经参照  https://hertzbeat.apache.org/docs/advanced/extend-http-example-token  实现同一个监控中token 的传递，但是 token 是给其它 监控指标使用，不是其它 监控，我期望的是 可以 跨 监控  使用 ，还有好的方式吗

**Comment by tomsun28** [comment]
no has others yet.
