### ISSUE TITLE
[Question] customize plugin not effective

### ISSUE THREAD

**Issue by zjh-Github** [apache/hertzbeat#2476]
### Question

my hertzbeat run in docker ,and add a customize plugin to ext-lib, this dir mounted, howerver no logs prints
version:1.6.0
![image](https://github.com/user-attachments/assets/f18c531a-be63-4079-a427-5064faa64eff)

![image](https://github.com/user-attachments/assets/5aa6d2ad-de5e-4d5e-b776-b7aa16017d7e)

**Comment by LiuTianyou** [comment]
hi, could you please check in the Alert Center whether an alert has been issued. According to the default availability threshold rule, an alert will be triggered only when data cannot be collected twice

**Comment by zjh-Github** [comment]
> hi, could you please check in the Alert Center whether an alert has been issued. According to the default availability threshold rule, an alert will be triggered only when data cannot be collected twice

the alarm was triggered normally and the Feishu robot received the alarm information.

**Comment by LiuTianyou** [comment]
hi, if you are using the already released version 1.6.0, put the plugin jar package to the ext-lib directory requires a restart for the plugin to take effect. If it is a version compiled from the master branch, you need to upload the plugin through the plugin management function. If these still cannot help you solve the problem, would you be willing to upload your plugin jar to help us reproduce this issue

**Comment by zjh-Github** [comment]
> hi, if you are using the already released version 1.6.0, put the plugin jar package to the ext-lib directory requires a restart for the plugin to take effect. If it is a version compiled from the master branch, you need to upload the plugin through the `Plugin manage` . If these still cannot help you solve the problem, would you be willing to upload your plugin jar to help us reproduce this issue

use version 1.6.0 and restart success .

**Comment by Yanshuming1** [comment]
> hi, if you are using the already released version 1.6.0, put the plugin jar package to the ext-lib directory requires a restart for the plugin to take effect. If it is a version compiled from the master branch, you need to upload the plugin through the `Plugin manage` . If these still cannot help you solve the problem, would you be willing to upload your plugin jar to help us reproduce this issue

Could it be that there is no reason for configuration in META-INF？

**Comment by LiuTianyou** [comment]
@zjh-Github  hi, you can try to reimplement a plugin class instead of modifying the default `DemoPluginImpl`. Since `DemoPluginImpl` has been packaged into the manager in hertzbeat-plugin, loading a class with the same name through ext-lib will not take effect. Please refer to https://hertzbeat.apache.org/docs/help/plugin to customize the plug-in

**Comment by zjh-Github** [comment]
> reimplement a plugin class

reimplement a plugin class is ok . thx

**Comment by zjh-Github** [comment]
> @zjh-Github hi, you can try to reimplement a plugin class instead of modifying the default `DemoPluginImpl`. Since `DemoPluginImpl` has been packaged into the manager in hertzbeat-plugin, loading a class with the same name through ext-lib will not take effect. Please refer to https://hertzbeat.apache.org/docs/help/plugin to customize the plug-in

reimplement a plugin class is ok . thx
