### ISSUE TITLE
docker环境下mysql无法链接

### ISSUE THREAD

**Issue by xiaoqiqiya** [apache/hertzbeat#2478]
### Question

已经在ext-lib添加mysql-connector-j-8.1.0.jar但是链接mysql还是无法使用
Query Error: No suitable driver found for jdbc:mysql
docker环境

**Comment by LiuTianyou** [comment]
hi，after adding the driver jar to ext-lib, you need to restart to take effect. please restart the hertzbeat service and try again

**Comment by xiaoqiqiya** [comment]
After restarting the program, it still cannot be connected normally

**Comment by xiaoqiqiya** [comment]
After restarting the program, it still cannot be connected normally

**Comment by pwallk** [comment]
hi, make sure the`ext-lib` directory is mounted correctly

**Comment by xiaoqiqiya** [comment]
docker  This file already exists in the container

**Comment by pwallk** [comment]
I have tested that both `mysql-connector-j-8.1.0.jar` and `mysql-connector-j-8.3.0.jar` work properly. Maybe you can provide the exception log

**Comment by xiaoqiqiya** [comment]
![Uploading 微信截图_20240806154741.png…]()

**Comment by xiaoqiqiya** [comment]
我看error没有报错

**Comment by xiaoqiqiya** [comment]
Query Error: No suitable driver found for    
how to solve
