### ISSUE TITLE
[BUG] 阈值规则关联告警没生效

### ISSUE THREAD

**Issue by zjh-Github** [apache/hertzbeat#2479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

新增centos的监控，在阈值规则中配置了关联监控，但是并没有真正关联，且没有开启全局

### Expected Behavior

配置之后正常关联

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

**Comment by tomsun28** [comment]
hi this is a known bug, will fix next version.

**Comment by zjh-Github** [comment]
> hi this is a known bug, will fix next version.

when is the next version?
