### ISSUE TITLE
[BUG] <Can not Edit Threshold Rule in master code>

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#2493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can not Edit Threshold Rule when use master code 

The click ok button not response. 

<img width="1194" alt="image" src="https://github.com/user-attachments/assets/04b01124-3466-449d-b844-a0499d3db23f">

### Environment

```markdown
HertzBeat version(s): master
```

**Comment by Aias00** [comment]
i will check this

**Comment by tomsun28** [comment]
> i will check this

sorry didn't see this. I already dealt with it.

**Comment by tomsun28** [comment]
Can you help review it https://github.com/apache/hertzbeat/pull/2494
