### ISSUE TITLE
[Question] Can the 'Remaining Days' field in SSL certificate monitoring be rounded down to an integer?

### ISSUE THREAD

**Issue by Kylin-Guo** [apache/hertzbeat#2520]
### Question

![image](https://github.com/user-attachments/assets/bd547ec7-8a30-49b6-b14e-cd42c649ab2d)

For instance, I want to get a reminder when there are 30 days left for a certain certificate. But because the 'Remaining Days' field is of numeric type, in the threshold I can only use days_remaining == 30. However, but it has decimal points like '30.8765', so the threshold won't be triggered.

**Comment by pwallk** [comment]
hi, you can try this
```java
equals(toInteger(days_remaining), 30)
```

**Comment by Kylin-Guo** [comment]
> hi, you can try this
> 
> ```java
> equals(toInteger(days_remaining), 30)
> ```

That is works, thx!
Just the threshold details page looks a little bit odd, because 'equals' & 'toInteger' didn't for numeric type.
Maybe 'equals' & 'toInteger' can be added to the selector in the next version?

**Comment by pwallk** [comment]
You can learn about `Apache Jexl`, or [refer](https://hertzbeat.apache.org/zh-cn/docs/help/alert_threshold_expr)
