### ISSUE TITLE
[BUG] <title>webhook send alter message error

### ISSUE THREAD

**Issue by Ykubernetes** [apache/hertzbeat#2524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During alarm recovery, sending a message containing a threshold expression causes the content field to contain special characters
for example：
{
  "alarmId": 76456,
  "target": "${target}",
  "thresholdId": 33455,
  "priority": 0,
  "content": "alert **** , status("up")",
  "status": 0,
  "times": 1,
  "triggerTime": "2022-02-25T13:32:13",
  "tags": {
    "app": "windows",
    "monitorId": "180427708350720",
    "metrics": "availability",
    "code": "UN_CONNECTABLE",
    "thresholdId": "112",
    "monitorName": "WINDOWS_192.168.124.12"
  }
}

"content"  is not a valid JSON format and has not been escaped

### Environment

```markdown
HertzBeat version(s): 1.6.0
```

### Debug logs

no logs

**Comment by Ykubernetes** [comment]
> hertzbeat 用于`Apache Jexl`处理表情，你可以详细了解它的使用方法，或者[参考](https://hertzbeat.apache.org/docs/help/alert_threshold_expr/)

!equals(status,"UP") 
There are double quotes. When sending notification recovery, adding this expression to the content field will cause a json format error.

**Comment by pwallk** [comment]
sorry，Reply wrong

**Comment by Ykubernetes** [comment]
> 抱歉，回复错误

这个方便解决吗

**Comment by Ykubernetes** [comment]
Why no one replied

**Comment by tomsun28** [comment]
Hi, this should be a problem caused by inserting special content into the json template. We will fix it by escaping it later.

**Comment by Ykubernetes** [comment]
> 你好，这应该是在 json 模板中插入特殊内容导致的问题，我们稍后会通过转义来修复。

好的
