### ISSUE TITLE
[BUG] After clicking Search in the Monitoring Center, the page will automatically refresh

### ISSUE THREAD

**Issue by milton4code** [apache/hertzbeat#2541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the monitoring center page, enter the query criteria in the search box and click Search to display normal results. But after about a minute, the page will automatically refresh and all data will be queried.

### Expected Behavior

the master 

### Steps To Reproduce

1. When you enter 11 parameters for query, the correct result will be returned.
![image](https://github.com/user-attachments/assets/ee8de5bc-f3c4-4ec9-95a8-221dfe2753e4)

Do not do anything and wait for about 1 minute. The page will automatically refresh and return all monitoring data. This is wrong.

![image](https://github.com/user-attachments/assets/71685ad0-8336-4cf0-b8ea-cd51d1a1f75a)

### Environment

```markdown
unrelease,the master default
```

**Comment by tomsun28** [comment]
solved by #2546

**Comment by milton4code** [comment]
excellent.666
