### ISSUE TITLE
[Task] <Add unit test> add `push` module dao unit test

### ISSUE THREAD

**Issue by yuluo-yx** [apache/hertzbeat#2563]
### Description

Adding unit tests to the push module's dao layer code

**Comment by TemirlanBasitov** [comment]
@yuluo-yx  Hi I can contribute

**Comment by yuluo-yx** [comment]
> @yuluo-yx Hi I can contribute

assign, pls go ahead. 👍

**Comment by TemirlanBasitov** [comment]
@yuluo-yx  check PR plz

**Comment by TemirlanBasitov** [comment]
@yuluo-yx  pls check https://github.com/apache/hertzbeat/pull/2614
