### ISSUE TITLE
[Task] support plugin parameters

### ISSUE THREAD

**Issue by LiuTianyou** [apache/hertzbeat#2591]
### Description

1. Allows users to define the parameters used by the plug-in when customizing the plug-in. For details, refer to parameter configuration of monitoring templates.
2. When enabling the plugin, let the user fill in the plugin parameters on the web-app
3. Add an interface definition for the post-alarm plugin that supports parameters
4. Maintain compatibility with `org.apache.hertzbeat.plugin.Plugin`

**Comment by Yanshuming1** [comment]
Please assign it to me

**Comment by Aias00** [comment]
assign me，pls
