### ISSUE TITLE
[Task] Add a pop-up window

### ISSUE THREAD

**Issue by Yanshuming1** [apache/hertzbeat#2600]
### Description

Render pop-ups based on the value returned by the backend
Click OK to pass parameters to the back end

**Comment by hritikchaudhary** [comment]
Hi @Yanshuming1 I'd like to contribute, where should I start?

**Comment by Yanshuming1** [comment]
> Hi @Yanshuming1 I'd like to contribute, where should I start?

I'm glad you could join me. I need to add a popup in the plugin Admin tab page, support dynamic rendering of the page according to the backend, and then click OK to save the data。

These are my two backend interface documents：https://www.yuque.com/cangjiantianya/qkgrtx/gf9f1m3mlp7sb27b
This is the demand issue ：https://github.com/apache/hertzbeat/issues/2591

**Comment by Yanshuming1** [comment]
> Hi @Yanshuming1 I'd like to contribute, where should I start?

If you can do it, I can assign it to you

**Comment by Yanshuming1** [comment]
> Hi @Yanshuming1 I'd like to contribute, where should I start?
There is another issue you can look at if you are interested：https://github.com/apache/hertzbeat/issues/2303

**Comment by hritikchaudhary** [comment]
I'm setting up the environment, how urgent is this?
I'll need little time to understand the project. You can assign either this or #2303. Whichever you think is better for me to start.
Thanks!

**Comment by Yanshuming1** [comment]
> I'm setting up the environment, how urgent is this?
> I'll need little time to understand the project. You can assign either this or #2303. Whichever you think is better for me to start.
> Thanks!

Then I designate 2023 for you， You can finish it in your own time

**Comment by Yanshuming1** [comment]
> I'm setting up the environment, how urgent is this? I'll need little time to understand the project. You can assign either this or #2303. Whichever you think is better for me to start. Thanks!

Please comment on 2023

**Comment by hritikchaudhary** [comment]
Commented on #2303
