### ISSUE TITLE
[BUG] [customize  dashboard]Multiple rows of data are not displayed correctly

### ISSUE THREAD

**Issue by zhangshenghang** [apache/hertzbeat#2663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Multiple rows of data are not displayed correctly
![image](https://github.com/user-attachments/assets/dc58e9e8-e1d6-4ae8-9a2e-b8ead63a3197)

### Environment

```markdown
HertzBeat version(s):
```

**Comment by zqr10159** [comment]
How to reproduce this bug

**Comment by kerwin612** [comment]
I have repeatedly tested the code from the latest branch several times but failed to reproduce the issue.
