### ISSUE TITLE
[Task] [customize dashboard] Jump to the specific monitoring page through the dashboard ID, which is more convenient to use

### ISSUE THREAD

**Issue by zhangshenghang** [apache/hertzbeat#2665]
### Description

Jump to the specific monitoring page through the dashboard ID, which is more convenient to use

<img width="648" alt="image" src="https://github.com/user-attachments/assets/39a4f2fd-306b-43c8-b4f7-5b1f7e0eec39">

**Comment by fr35wo** [comment]
I want to challenge that issue. I'm a beginner so I need a lot of time and help. Is that okay?
