### ISSUE TITLE
[Question] should we allow define multi tags with same name?

### ISSUE THREAD

**Issue by Aias00** [apache/hertzbeat#2690]
### Question

should we allow define multi tags with same name?

in my test, i can create multi tags with same name. 

<img width="373" alt="image" src="https://github.com/user-attachments/assets/261c955c-5277-4edc-b31c-09ec73f58bb2">

but after i binded the tags to a monitor

<img width="586" alt="image" src="https://github.com/user-attachments/assets/188187a9-7a10-4ae9-8126-e0024d983a36">

the monitor list just shows one tag

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/79628539-ebc8-40d4-97b7-3444d27399e5">

**Comment by Aias00** [comment]
also, when selecting tags at creating status componment 
<img width="690" alt="image" src="https://github.com/user-attachments/assets/b7104fed-b529-42fb-84f0-de1efeff48e0">

**Comment by tomsun28** [comment]
hi we allow the same tag name with different value, like `logic:xxx, logic:bbb`. but not allow the same name with same value, eg: `logic:aa, logic:aa, logic, logic`

<img width="615" alt="image" src="https://github.com/user-attachments/assets/1c761ce1-2e28-4ac2-ab0a-e803156d6c11">

here seem it is a bug, the tag value does not dispaly.

**Comment by Aias00** [comment]
> hi we allow the same tag name with different value, like `logic:xxx, logic:bbb`. but not allow the same name with same value, eg: `logic:aa, logic:aa, logic, logic`
> 
> <img alt="image" width="615" src="https://private-user-images.githubusercontent.com/24788200/365484174-1c761ce1-2e28-4ac2-ab0a-e803156d6c11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDU0NzksIm5iZiI6MTcyNTg0NTE3OSwicGF0aCI6Ii8yNDc4ODIwMC8zNjU0ODQxNzQtMWM3NjFjZTEtMmUyOC00YWMyLWFiMGEtZTgwMzE1NmQ2YzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAxMjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OWRjMjM2MTA4YmNmOTljNTlmZWJjMWM3ODNmMzdlMzhjMzlhMmZhZTg4YzdmODA5ZjVjYTNhN2FkMjI4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n-rLfQDXrog_Dz705Iz1ME1hQMDDfqJzaBqi5ABXpWk">
> here seem it is a bug, the tag value does not dispaly.

i set empty value for those same name tags. i can try filling values for them

**Comment by Aias00** [comment]
> hi we allow the same tag name with different value, like `logic:xxx, logic:bbb`. but not allow the same name with same value, eg: `logic:aa, logic:aa, logic, logic`
> 
> <img alt="image" width="615" src="https://private-user-images.githubusercontent.com/24788200/365484174-1c761ce1-2e28-4ac2-ab0a-e803156d6c11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDY3NzUsIm5iZiI6MTcyNTk0NjQ3NSwicGF0aCI6Ii8yNDc4ODIwMC8zNjU0ODQxNzQtMWM3NjFjZTEtMmUyOC00YWMyLWFiMGEtZTgwMzE1NmQ2YzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA1MzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MDJlOWRmMzNhNDhiNDliYzYzZGJkZDc2OGM4NGU2ODYwNWQwOTU2MDI3ZmE3Yjc3NDhjYjk1Y2E2MDBlNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eB8w_8UUlI-mKqYrKfEz32eyBU0ZAOW-0YjU094u3jE">
> here seem it is a bug, the tag value does not dispaly.

actually, i found we can define multi same key tags with same value 
<img width="279" alt="image" src="https://github.com/user-attachments/assets/2a8ff553-f05e-4600-ab5e-ac0152e01ca3">
