### ISSUE TITLE
[BUG] Threshold Rules search i18n error

### ISSUE THREAD

**Issue by Aias00** [apache/hertzbeat#2692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

under Simplified Chinese Lang

in rules list, there are multi items, there`s name contains "数据":

<img width="1240" alt="image" src="https://github.com/user-attachments/assets/b883bc99-fbba-4fd8-ae35-2a57a81b662f">

but when input "数据" to search , there will be no data in response

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/90969205-8e0d-4991-a230-d7781221a198">

### Expected Behavior

when the input search param is right, return right data

### Environment

```markdown
HertzBeat version(s): master
```

### Debug logs

sql: 2024-09-08 19:48:32.341--ClientSession(63600584)--Connection(1612357524)--SELECT id AS a1, app AS a2, creator AS a3, enable AS a4, expr AS a5, field AS a6, gmt_create AS a7, gmt_update AS a8, metric AS a9, modifier AS a10, preset AS a11, priority AS a12, recover_notice AS a13, tags AS a14, template AS a15, times AS a16 FROM hzb_alert_define WHERE ((((LOWER(app) LIKE ? OR LOWER(metric) LIKE ?) OR LOWER(field) LIKE ?) OR LOWER(expr) LIKE ?) OR LOWER(template) LIKE ?) ORDER BY id DESC LIMIT ?, ?
	bind => [%数据%, %数据%, %数据%, %数据%, %数据%, 0, 8]

**Comment by Aias00** [comment]
cause database just save app by english, and no auto translation when searching 
<img width="209" alt="image" src="https://github.com/user-attachments/assets/b7d6231d-946a-4f6b-a773-91a56006b13c">

**Comment by keaifafafa** [comment]
Hello，I want to try it.

**Comment by Aias00** [comment]
> Hello，I want to try it.

OK, thanks for ur time

**Comment by tomsun28** [comment]
> Hello，I want to try it.

👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.

**Comment by Aias00** [comment]
> > Hello，I want to try it.
> 
> 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.

@keaifafafa yes, pls don not change the store content, and just translate Chinese to app name , then do the search logic

**Comment by keaifafafa** [comment]
Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW.  Then I will add request params in web front when new threshold rules.  TRANSLATIONS paramas styles like it that "{
  "en-US": "Prometheus Task / Monitor Availability",
  "zh-CN": "Prometheus任务 / 监控可用性",
  "zh-TW": "Prometheus任务 / 監控可用性"
}".     It will match this params when searching.    What do you about it?

**Comment by keaifafafa** [comment]
> > Hello，I want to try it.
> 
> 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.

Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{
"en-US": "Prometheus Task / Monitor Availability",
"zh-CN": "Prometheus任务 / 监控可用性",
"zh-TW": "Prometheus任务 / 監控可用性"
}". It will match this params when searching. What do you about it?

**Comment by Aias00** [comment]
> > > Hello，I want to try it.
> > 
> > 
> > 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.
> 
> Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{ "en-US": "Prometheus Task / Monitor Availability", "zh-CN": "Prometheus任务 / 监控可用性", "zh-TW": "Prometheus任务 / 監控可用性" }". It will match this params when searching. What do you about it?

no, don not need to add any  column, cause u can translate the search content to saved content

**Comment by keaifafafa** [comment]
> > > > Hello，I want to try it.
> > > 
> > > 
> > > 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.
> > 
> > 
> > Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{ "en-US": "Prometheus Task / Monitor Availability", "zh-CN": "Prometheus任务 / 监控可用性", "zh-TW": "Prometheus任务 / 監控可用性" }". It will match this params when searching. What do you about it?
> 
> no, don not need to add any column, cause u can translate the search content to saved content

OK，I can new yml to translate the search contnet to saved content. Like this pic below
![image](https://github.com/user-attachments/assets/978a1229-e366-47af-9e40-f78d42a6bbc0)

**Comment by Aias00** [comment]
> > > > > Hello，I want to try it.
> > > > 
> > > > 
> > > > 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.
> > > 
> > > 
> > > Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{ "en-US": "Prometheus Task / Monitor Availability", "zh-CN": "Prometheus任务 / 监控可用性", "zh-TW": "Prometheus任务 / 監控可用性" }". It will match this params when searching. What do you about it?
> > 
> > 
> > no, don not need to add any column, cause u can translate the search content to saved content
> 
> OK，I can new yml to translate the search contnet to saved content. Like this pic below ![image](https://private-user-images.githubusercontent.com/83876361/367583713-978a1229-e366-47af-9e40-f78d42a6bbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDcwNDAsIm5iZiI6MTcyNjQwNjc0MCwicGF0aCI6Ii84Mzg3NjM2MS8zNjc1ODM3MTMtOTc4YTEyMjktZTM2Ni00N2FmLTllNDAtZjc4ZDQyYTZiYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMGNiNGZmYWMzMTE5NTY2OTdlNGM2YWZhZmQxMDFlNTkzZWVjMGExMjZkODA5NDE5YTBlYWIwMzM3ZGE1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Tv9_7HPYFfNDarWuQCra0M1N75IwPvF36f66yTHjXA)

hi, maybe u can try i18n. Search this keyword in project~

**Comment by keaifafafa** [comment]
> hi, maybe u can try i18n. Search this keyword in project~

Sorry, I can not understant completely what your mens compleltely. And, i18n is implemented on the web front end.  Could tell me some details?   You means it that I should mappping other lang in yml, example for en-US and en-TW?

**Comment by keaifafafa** [comment]
> > > > > > Hello，I want to try it.
> > > > > 
> > > > > 
> > > > > 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.
> > > > 
> > > > 
> > > > Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{ "en-US": "Prometheus Task / Monitor Availability", "zh-CN": "Prometheus任务 / 监控可用性", "zh-TW": "Prometheus任务 / 監控可用性" }". It will match this params when searching. What do you about it?
> > > 
> > > 
> > > no, don not need to add any column, cause u can translate the search content to saved content
> > 
> > 
> > OK，I can new yml to translate the search contnet to saved content. Like this pic below ![image](https://private-user-images.githubusercontent.com/83876361/367583713-978a1229-e366-47af-9e40-f78d42a6bbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDcwNDAsIm5iZiI6MTcyNjQwNjc0MCwicGF0aCI6Ii84Mzg3NjM2MS8zNjc1ODM3MTMtOTc4YTEyMjktZTM2Ni00N2FmLTllNDAtZjc4ZDQyYTZiYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMGNiNGZmYWMzMTE5NTY2OTdlNGM2YWZhZmQxMDFlNTkzZWVjMGExMjZkODA5NDE5YTBlYWIwMzM3ZGE1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Tv9_7HPYFfNDarWuQCra0M1N75IwPvF36f66yTHjXA)
> 
> hi, maybe u can try i18n. Search this keyword in project~

Sorry, I can not understant completely what your mens compleltely. And, i18n is implemented on the web front end. Could tell me some details? You means it that I should mappping other lang in yml, example for en-US and zh-TW?

**Comment by Aias00** [comment]
> > > > > > > Hello，I want to try it.
> > > > > > 
> > > > > > 
> > > > > > 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.
> > > > > 
> > > > > 
> > > > > Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{ "en-US": "Prometheus Task / Monitor Availability", "zh-CN": "Prometheus任务 / 监控可用性", "zh-TW": "Prometheus任务 / 監控可用性" }". It will match this params when searching. What do you about it?
> > > > 
> > > > 
> > > > no, don not need to add any column, cause u can translate the search content to saved content
> > > 
> > > 
> > > OK，I can new yml to translate the search contnet to saved content. Like this pic below ![image](https://private-user-images.githubusercontent.com/83876361/367583713-978a1229-e366-47af-9e40-f78d42a6bbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDcwNDAsIm5iZiI6MTcyNjQwNjc0MCwicGF0aCI6Ii84Mzg3NjM2MS8zNjc1ODM3MTMtOTc4YTEyMjktZTM2Ni00N2FmLTllNDAtZjc4ZDQyYTZiYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMGNiNGZmYWMzMTE5NTY2OTdlNGM2YWZhZmQxMDFlNTkzZWVjMGExMjZkODA5NDE5YTBlYWIwMzM3ZGE1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Tv9_7HPYFfNDarWuQCra0M1N75IwPvF36f66yTHjXA)
> > 
> > 
> > hi, maybe u can try i18n. Search this keyword in project~
> 
> Sorry, I can not understant completely what your mens compleltely. And, i18n is implemented on the web front end. Could tell me some details? You means it that I should mappping other lang in yml, example for en-US and zh-TW?

refer this: org.apache.hertzbeat.manager.service.impl.AppServiceImpl#getI18nApps

**Comment by keaifafafa** [comment]
> > > > > > > > Hello，I want to try it.
> > > > > > > 
> > > > > > > 
> > > > > > > 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.
> > > > > > 
> > > > > > 
> > > > > > Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{ "en-US": "Prometheus Task / Monitor Availability", "zh-CN": "Prometheus任务 / 监控可用性", "zh-TW": "Prometheus任务 / 監控可用性" }". It will match this params when searching. What do you about it?
> > > > > 
> > > > > 
> > > > > no, don not need to add any column, cause u can translate the search content to saved content
> > > > 
> > > > 
> > > > OK，I can new yml to translate the search contnet to saved content. Like this pic below ![image](https://private-user-images.githubusercontent.com/83876361/367583713-978a1229-e366-47af-9e40-f78d42a6bbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDcwNDAsIm5iZiI6MTcyNjQwNjc0MCwicGF0aCI6Ii84Mzg3NjM2MS8zNjc1ODM3MTMtOTc4YTEyMjktZTM2Ni00N2FmLTllNDAtZjc4ZDQyYTZiYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMGNiNGZmYWMzMTE5NTY2OTdlNGM2YWZhZmQxMDFlNTkzZWVjMGExMjZkODA5NDE5YTBlYWIwMzM3ZGE1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Tv9_7HPYFfNDarWuQCra0M1N75IwPvF36f66yTHjXA)
> > > 
> > > 
> > > hi, maybe u can try i18n. Search this keyword in project~
> > 
> > 
> > Sorry, I can not understant completely what your mens compleltely. And, i18n is implemented on the web front end. Could tell me some details? You means it that I should mappping other lang in yml, example for en-US and zh-TW?
> 
> refer this: org.apache.hertzbeat.manager.service.impl.AppServiceImpl#getI18nApps
Thanks, I know what you means.  But now it has a probleam that alerter module can not depend on manager module.  Can I implement the alerter module  to call the manager module's interface using HttpClient? Do you have better plans？

**Comment by keaifafafa** [comment]
> > > > > > > > Hello，I want to try it.
> > > > > > > 
> > > > > > > 
> > > > > > > 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.
> > > > > > 
> > > > > > 
> > > > > > Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{ "en-US": "Prometheus Task / Monitor Availability", "zh-CN": "Prometheus任务 / 监控可用性", "zh-TW": "Prometheus任务 / 監控可用性" }". It will match this params when searching. What do you about it?
> > > > > 
> > > > > 
> > > > > no, don not need to add any column, cause u can translate the search content to saved content
> > > > 
> > > > 
> > > > OK，I can new yml to translate the search contnet to saved content. Like this pic below ![image](https://private-user-images.githubusercontent.com/83876361/367583713-978a1229-e366-47af-9e40-f78d42a6bbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDcwNDAsIm5iZiI6MTcyNjQwNjc0MCwicGF0aCI6Ii84Mzg3NjM2MS8zNjc1ODM3MTMtOTc4YTEyMjktZTM2Ni00N2FmLTllNDAtZjc4ZDQyYTZiYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMGNiNGZmYWMzMTE5NTY2OTdlNGM2YWZhZmQxMDFlNTkzZWVjMGExMjZkODA5NDE5YTBlYWIwMzM3ZGE1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Tv9_7HPYFfNDarWuQCra0M1N75IwPvF36f66yTHjXA)
> > > 
> > > 
> > > hi, maybe u can try i18n. Search this keyword in project~
> > 
> > 
> > Sorry, I can not understant completely what your mens compleltely. And, i18n is implemented on the web front end. Could tell me some details? You means it that I should mappping other lang in yml, example for en-US and zh-TW?
> 
> refer this: org.apache.hertzbeat.manager.service.impl.AppServiceImpl#getI18nApps

Thanks, I know what you means. But now it has a probleam that alerter module can not depend on manager module. Can I implement the alerter module to call the manager module's interface using HttpClient? Do you have better plans？

**Comment by Aias00** [comment]
> > > > > > > > > Hello，I want to try it.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 👍 Hi, it is recommended to still store the `app name` in the database unchanged, and add a match from the monitoring template yml mapping content when searching.
> > > > > > > 
> > > > > > > 
> > > > > > > Hi，my idea is add new column TRANSLATIONS in table HZB_ALERT_DEFINE for store translate content with en-US、zh-CN、zh-TW. Then I will add request params in web front when new threshold rules. TRANSLATIONS paramas styles like it that "{ "en-US": "Prometheus Task / Monitor Availability", "zh-CN": "Prometheus任务 / 监控可用性", "zh-TW": "Prometheus任务 / 監控可用性" }". It will match this params when searching. What do you about it?
> > > > > > 
> > > > > > 
> > > > > > no, don not need to add any column, cause u can translate the search content to saved content
> > > > > 
> > > > > 
> > > > > OK，I can new yml to translate the search contnet to saved content. Like this pic below ![image](https://private-user-images.githubusercontent.com/83876361/367583713-978a1229-e366-47af-9e40-f78d42a6bbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDcwNDAsIm5iZiI6MTcyNjQwNjc0MCwicGF0aCI6Ii84Mzg3NjM2MS8zNjc1ODM3MTMtOTc4YTEyMjktZTM2Ni00N2FmLTllNDAtZjc4ZDQyYTZiYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMjU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMGNiNGZmYWMzMTE5NTY2OTdlNGM2YWZhZmQxMDFlNTkzZWVjMGExMjZkODA5NDE5YTBlYWIwMzM3ZGE1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Tv9_7HPYFfNDarWuQCra0M1N75IwPvF36f66yTHjXA)
> > > > 
> > > > 
> > > > hi, maybe u can try i18n. Search this keyword in project~
> > > 
> > > 
> > > Sorry, I can not understant completely what your mens compleltely. And, i18n is implemented on the web front end. Could tell me some details? You means it that I should mappping other lang in yml, example for en-US and zh-TW?
> > 
> > 
> > refer this: org.apache.hertzbeat.manager.service.impl.AppServiceImpl#getI18nApps
> 
> Thanks, I know what you means. But now it has a probleam that alerter module can not depend on manager module. Can I implement the alerter module to call the manager module's interface using HttpClient? Do you have better plans？

of couse u can
