### ISSUE TITLE
[BUG] The status collection error of containers in Docker monitoring

### ISSUE THREAD

**Issue by whls** [apache/hertzbeat#2696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When use docker monitoring template  to collect the container status, 0 is displayed.

### Expected Behavior

The collected information should be similar to: "Up 5 days"

### Environment

```markdown
HertzBeat version(s): v1.5.0
```

**Comment by Aias00** [comment]
didn`t recurrent in master branch, maybe this had already been fixed

**Comment by whls** [comment]
> didn`t recurrent in master branch, maybe this had already been fixed
Thank you for your answer. I will use the new version ：）
