### ISSUE TITLE
[BUG] 界面主题刷新或者重启浏览器会恢复到默认状态

### ISSUE THREAD

**Issue by MisterAnley** [apache/hertzbeat#2703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在系统设置中更新设置主题后，强制刷新浏览器或者重启浏览器后，主题会变回默认状态

### Environment

```markdown
HertzBeat version(s):
```

**Comment by pwallk** [comment]
same issues: #2269 
pr: #2321
