### ISSUE TITLE
[Question] <title> K8S 部署的hertzbeat新增Kubernets监控测试连接失败 

### ISSUE THREAD

**Issue by Figure43** [apache/hertzbeat#2711]
### Question

![image](https://github.com/user-attachments/assets/f50f24c7-c063-429a-8bd1-f56d995ba976)
环境： 
Kubernetes：v1.28
hertzbeat:1.6.0

在监控中心添加监控K8S 无法连接，按照 使用指南中的 方法二获取的Token

**Comment by zhzhy86** [comment]
同上问题，我用的是K3S v1.29

**Comment by LiuTianyou** [comment]
@Figure43 Hi, please make sure the apiServer port is correct and open, the hertzbeat and apiServer networks are interconnected.
If you are already using Kubernetes Dashboard, you can use the same token you use to log in to Kubernetes Dashboard to configure monitoring.

**Comment by LiuTianyou** [comment]
@zhzhy86   If you are already using Kubernetes Dashboard, you can use the same token you use to log in to Kubernetes Dashboard to configure monitoring.
Or you can try to get a token and configure monitoring by following the steps below:

```shell

kubectl create serviceaccount dashboard-admin -n kube-system

kubectl create clusterrolebinding dashboard-admin --clusterrole=cluster-admin --serviceaccount=kube-system:dashboard-admin

# This token will expire after 24 hours

kubectl create token dashboard-admin -n kube-system --duration=24h

```

I tested in k3s v1.28.2 and was able to get the token and configure it in hertzebeat

**Comment by LiuTianyou** [comment]
please refer to https://github.com/apache/hertzbeat/issues/2096 to modify the monitoring template
