### ISSUE TITLE
[Question] <title>snmpv3 OOM

### ISSUE THREAD

**Issue by hxJava666** [apache/hertzbeat#2725]
### Question

使用snmpv3监控时候，程序运行一段时间会报OOM异常，通过分析head.dump分析对应的对象，已经手动释放但是还是会有OOM

**Comment by hxJava666** [comment]
![image](https://github.com/user-attachments/assets/b5d39a50-8c2f-4154-b5b8-67a67b9e2ef3)使用源代码snmp远程连接不了，就修改了下没有放到缓存里

**Comment by tomsun28** [comment]
> ![image](https://private-user-images.githubusercontent.com/81760154/368949456-b5d39a50-8c2f-4154-b5b8-67a67b9e2ef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzU3MTAsIm5iZiI6MTcyNzI3NTQxMCwicGF0aCI6Ii84MTc2MDE1NC8zNjg5NDk0NTYtYjVkMzlhNTAtOGMyZi00MTU0LWI1YjgtNjdhNjdiOWUyZWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOWIyNzE5MWQ1M2FlMWEzY2FhZTI2NzBjMjY2ZDQzMTg3YjljZTczMGRlYmJjZWFjOTEwZTRjZjgwYWI0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.om0MxqQ1rv8OP-4szPYVigjUVCcwhZ8qh39AkAbjCe0)使用源代码snmp远程连接不了，就修改了下没有放到缓存里

hi, is this fixed?

**Comment by hxJava666** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/81760154/368949456-b5d39a50-8c2f-4154-b5b8-67a67b9e2ef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzU3MTAsIm5iZiI6MTcyNzI3NTQxMCwicGF0aCI6Ii84MTc2MDE1NC8zNjg5NDk0NTYtYjVkMzlhNTAtOGMyZi00MTU0LWI1YjgtNjdhNjdiOWUyZWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOWIyNzE5MWQ1M2FlMWEzY2FhZTI2NzBjMjY2ZDQzMTg3YjljZTczMGRlYmJjZWFjOTEwZTRjZjgwYWI0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.om0MxqQ1rv8OP-4szPYVigjUVCcwhZ8qh39AkAbjCe0)使用源代码snmp远程连接不了，就修改了下没有放到缓存里
> 
> 嗨，这是固定的吗？

是的，这个是固定这样的，OOM问题解决了，不是这里的问题，是某个任务队列里面任务没有及时消费导致的任务堆积问题

**Comment by tomsun28** [comment]
hi 方便可以贴一下解决方案
