### ISSUE TITLE
[Question] I did not get the desired result using SNMP.

### ISSUE THREAD

**Issue by MaNong889** [apache/hertzbeat#2740]
### Question

When I use a custom SNMP template to retrieve the power status and fan status, the value is not 'OK', but the number 4 and 3.
![image](https://github.com/user-attachments/assets/a148635c-185d-41e6-a923-fb375fb4a015)
![image](https://github.com/user-attachments/assets/59fc46d8-5153-402b-84b4-f7035e826093)
![image](https://github.com/user-attachments/assets/f2511350-42d3-4996-8c39-4e5ddb6cd3e4)
![image](https://github.com/user-attachments/assets/43506589-510c-4d70-aa3d-524135e73d59)
![image](https://github.com/user-attachments/assets/8aeb6e3f-9d54-4245-8fde-34f97cbfffd0)

**Comment by MaNong889** [comment]
![image](https://github.com/user-attachments/assets/e7ea704c-9210-4722-a53a-9f4df9e79345)
Why is my field type set to 1, but instead of getting a string, it retrieves a number?

**Comment by zuobiao-zhou** [comment]
Since the code returns a number instead of the string you were expecting, could you help us fix it?

**Comment by MaNong889** [comment]
or (VariableBinding binding : vbs) {
    if (binding == null) {
        continue;
    }
    
    Variable variable = binding.getVariable();
    String value;

    if (variable instanceof TimeTicks timeTicks) {
        String timeValue = timeTicks.toString(FORMAT_PATTERN);
        oidsValueMap.put(binding.getOid().toDottedString(), timeValue);
    } else {
        String valueString = binding.toValueString();
        if (valueString.matches("^[a-zA-Z]+\\(\\d+\\)$")) {
            value = valueString.substring(0, valueString.indexOf("(")).trim();
        } else {
            value = valueString; 
        }
        oidsValueMap.put(binding.getOid().toDottedString(), value);
    }
}
I am an operations engineer and I don't understand Java code. However, I sent the SnmpCollectImpl.java file to ChatGPT, and it helped me write a chunk of code that I replaced in the data collection part of SnmpCollectImpl.java. But the compilation keeps failing, and I can't resolve it. What should I do?

**Comment by zuobiao-zhou** [comment]
Hello, in our project, we utilize snmp4j to implement the SNMP protocol. When performing GET operations to query the power status or fan status, snmp4j only provides a numerical representation of the query results. As shown in your command line screenshot, a value of 4 for power status indicates that the power is on, while a value of 3 for fan status indicates that the fan is operating normally. This is reflected in the code snippet `oidsValueMap.put(binding.getOid().toDottedString(), binding.toValueString());` within `snmpCollectImpl.java`.

Although this approach is not as intuitive as using "on" or "ok", it does function properly, and we can still set up alerts based on these values. Currently, I haven't come up with an optimal solution to make the outputs more descriptive.

**Comment by MaNong889** [comment]
ok,thanks
