### ISSUE TITLE
[Question] <Why do all the metrics in my historical graphs show '{}'?>

### ISSUE THREAD

**Issue by MaNong889** [apache/hertzbeat#2746]
### Question

Why do all the metrics in my historical graphs show '{}'? How can I get the specific metric names on the charts, as shown
![image](https://github.com/user-attachments/assets/43a1a3d7-cbbd-4867-8e77-e0388363b50d)

**Comment by zqr10159** [comment]
Because the default monitoring template does not set the label, set the label to true in the field you want to display can be displayed

**Comment by MaNong889** [comment]
![image](https://github.com/user-attachments/assets/740249db-3f81-40da-bb80-b6723b07ecaf)
![image](https://github.com/user-attachments/assets/9e151c50-df24-4435-b874-dc272a47b334)
![image](https://github.com/user-attachments/assets/08ea3513-d540-4996-8f42-d3bfe804d884)
When I set label: true, I can see the data in real-time monitoring, but the historical chart does not display any graph. Please refer to the images above.

**Comment by MaNong889** [comment]
?How to solve this issue，please?

**Comment by MaNong889** [comment]
> Because the default monitoring template does not set the label, set the label to true in the field you want to display can be displayed

?How to solve this issue，please?
