### ISSUE TITLE
[BUG]Huawei JDK image download address is wrong

### ISSUE THREAD

**Issue by pruidong** [apache/hertzbeat#2747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[https://hertzbeat.apache.org/zh-cn/docs/start/package-deploy#%E5%AE%89%E8%A3%85%E5%8C%85%E9%83%A8%E7%BD%B2%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98](url)

Huawei does not have a JDK 17 installation package in the JDK image download. It is recommended to remove the address. thanks.

### Expected Behavior

It is recommended to remove the address. thanks.

### Steps To Reproduce

open [https://hertzbeat.apache.org/zh-cn/docs/start/package-deploy#%E5%AE%89%E8%A3%85%E5%8C%85%E9%83%A8%E7%BD%B2%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98](url)

### Environment

```markdown
HertzBeat version(s):
```

**Comment by tomsun28** [comment]
thanks, can you help us remove it.
