### ISSUE TITLE
[BUG] <title>1.5版本的监控导入到1.6版本报错 json文件导入

### ISSUE THREAD

**Issue by hermit2018** [apache/hertzbeat#2769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

导入 json 文件报错Params field snmpyersion is required 将json 文件中version替换为snmpversion 依然报错
![微信图片_20241010094441](https://github.com/user-attachments/assets/3b0a1453-8591-4ddd-96b9-6c5e8a12e399)

### Expected Behavior

正常导入成功

### Environment

```markdown
HertzBeat version(s):v1.60
```

### Debug logs

无

### Anything else?

吴

**Comment by zuobiao-zhou** [comment]
Change "version" to "snmpVersion" in the SNMP protocol monitoring, and ensure that the "V" is uppercase.
