### ISSUE TITLE
[BUG] <title>The text format of startup.sh and shutdown.sh is incorrect

### ISSUE THREAD

**Issue by yangshuDBA** [apache/hertzbeat#2770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The text format of startup.sh and shutdown.sh is incorrect。
both this is need to set unix format。
![image](https://github.com/user-attachments/assets/52b66286-d63b-4eae-b5fd-1f15a50d13d2)

### Environment

```markdown
HertzBeat version(s):V1.6.1.RC4
```

**Comment by yangshuDBA** [comment]
restart.sh  is also incorrect 
![image](https://github.com/user-attachments/assets/9d6ce6fd-1dd9-4019-99a3-e1a91e8740f2)

**Comment by zuobiao-zhou** [comment]
Hi, this is a pre-release version. You are welcome to provide feedback via the mailing list.

**Comment by zqr10159** [comment]
We will fix it.
