### ISSUE TITLE
[BUG] When you choose to enable HTTPS, the port will be changed back to 443 by default.

### ISSUE THREAD

**Issue by shenliehuozhi** [apache/hertzbeat#2779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我打算新建一个https页面可用性监测，按要求填写后
![image](https://github.com/user-attachments/assets/38c4a968-a341-4c73-a166-a60066633202)
因为是https页面，点击开启https，此时端口会变成默认的443端口
![image](https://github.com/user-attachments/assets/ab1add8d-935d-46b7-905c-f4764f3eb3d3)
如果稍不注意，就会导致配置错误。

### Expected Behavior

建议将开启HTTPS这个选项，调整到端口选项前面，这样开启HTTPS默认是443，但是端口选项在后面，用户明白还需修改对应端口号
![image](https://github.com/user-attachments/assets/51472ff4-cd2f-4e1c-b21a-cd5057d76caa)

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

**Comment by zuobiao-zhou** [comment]
> hi, this is a feature, auto config default ssl port 443.

However, when a user manually changes an HTTPS port number, clicking the "Enable HTTPS" button forces the port number back to 443. It may be better if the button only sets the default value; when the user has already modified the port, clicking "Enable HTTPS" should leave the port number unchanged.
