### ISSUE TITLE
[Question] no prometheus history data 

### ISSUE THREAD

**Issue by tianbo-0319** [apache/hertzbeat#2790]
### Question

![QQ_1730170325338](https://github.com/user-attachments/assets/5d525968-dc3f-4e2d-a089-ab1a7f027bbd)
prometheus任务没有历史数据是咋回事呀？实时的有数据，其他监控也都有历史，版本1.5.0，数据存储用的taos

**Comment by zqr10159** [comment]
tdengine does not support Prometheus format data, you can use victoriaMetrics
