### ISSUE TITLE
[BUG] 企业微信应用消息在微信中查看提示“暂不支持此消息类型，请在企业微信中查看”

### ISSUE THREAD

**Issue by shenliehuozhi** [apache/hertzbeat#2791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

配置好企业微信应用后，测试发现告警信息在微信中查看会提示“暂不支持此消息类型，请在企业微信中查看”

-  企业微信正常显示，从消息内容看，消息格式应该是markdown格式的

![image](https://github.com/user-attachments/assets/c2617f1b-d07e-4333-971b-9b5a6a45e87f)
- 微信提示“暂不支持此消息类型，请在企业微信中查看”
![image](https://github.com/user-attachments/assets/2b45e845-35f5-4e16-b8f8-808e489471f8)

### Expected Behavior

经过查阅资料了解到是微信端不支持markdown消息，只支持文本类消息，从目前企业微信应用告警的内容看，对格式化要求并不高，建议能够提供选项让用户选择是否需要在微信中查看消息，如果选择是，则将告警信息以文本消息发送而非markdown格式。

### Environment

```markdown
HertzBeat version(s):Apache HertzBeat (incubating) v1.6.0
```

### Anything else?

感谢开发者们

**Comment by tomsun28** [comment]
hi, WeChat for Business application messages are recommended to be viewed in WeChat for Business

**Comment by gaows20** [comment]
可以使用饭碗警告做一次转发就可以了。hertzbeat webhook传到https://fwalert.com/  ，然后饭碗告警提取参数 重新推送至企业微信应用就可以了。或者自建wehbhook做转发。
