### ISSUE TITLE
Monitoring in the intranet environment

### ISSUE THREAD

**Issue by ziyiGithub** [apache/hertzbeat#2803]
### Question

The monitored party is in an intranet environment. A port is opened to send alarm messages through MQTT. Can I monitor MQTT messages to achieve monitoring?

**Comment by LiuTianyou** [comment]
Hi, can the intranet access the external network? If so, you can deploy the collector on the intranet and the management on the external network to implement the monitoring function.

**Comment by ziyiGithub** [comment]
> Hi, can the intranet access the external network? If so, you can deploy the collector on the intranet and the management on the external network to implement the monitoring function.
Thank you very much for your idea. It has made the project much clearer to me now. This is indeed a feasible solution. Thank you very much for your help!
