### ISSUE TITLE
[BUG] 通过SNMP采集Windows的存储信息时,因为磁盘空间过大出现负数

### ISSUE THREAD

**Issue by IanWu** [apache/hertzbeat#2828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

通过SNMP采集Windows的存储信息时,因为磁盘空间过大出现负数
<img width="1133" alt="企业微信截图_17322478389593" src="https://github.com/user-attachments/assets/cbe3258e-1901-46af-a11d-00d865ddc8bf">

### Expected Behavior

磁盘空间大小、存储空闲、存储占用返回为正整数并且存储空闲+存储占用=磁盘空间大小

### Environment

```markdown
HertzBeat version(s):1.6.1
```

**Comment by starryCoder** [comment]
i can do it，please assign to me

**Comment by starryCoder** [comment]
hi，after my debug， I found that the original data was negative
![image](https://github.com/user-attachments/assets/9e3199dc-f4c3-4d87-b7e9-44d8a0ecc489

**Comment by LiuTianyou** [comment]
@starryCoder hi, if the original data is wrong, this is a problem with SNMP and there is no way to solve it by modifying hertzbeat. Thank you for your contribution
