### ISSUE TITLE
Suggest adding support for common protocols such as Modbus and PLC

### ISSUE THREAD

**Issue by boyucjz** [apache/hertzbeat#2839]
### Description

建议增加对modbus及PLC常用协议的支持

### Task List
1.集成PLC4X开源库
2.增加plc监控接口
3.前端管理界面补充
_No response_

**Comment by ZY945** [comment]
Here are some relevant libraries and documents that I have found through my search
以下是我查询到的一些相关库和文档
https://plc4x.apache.org/plc4x/0.12.0/users/getting-started/plc4j.html#_using_the_plc4j_api_directly
https://plc4x.apache.org/plc4x/0.12.0/users/getting-started/virtual-modbus.html
https://mvnrepository.com/artifact/org.apache.plc4x/plc4j-api/0.12.0
https://mvnrepository.com/artifact/org.apache.plc4x/plc4j-driver-modbus/0.12.0
<img width="1728" alt="ModBus-1" src="https://github.com/user-attachments/assets/4b42fb61-cfa9-44e7-9779-6a6b2b10ab14">

**Comment by ZY945** [comment]
<img width="1719" alt="image" src="https://github.com/user-attachments/assets/1f26e791-d0f4-4df0-8db3-746605b13b46">
<img width="990" alt="image" src="https://github.com/user-attachments/assets/03034147-dc1b-4f8c-8ca6-e2df06f1a7af">
<img width="983" alt="image" src="https://github.com/user-attachments/assets/7e6898e2-30bc-477f-a63b-921fb46824ca">
<img width="1715" alt="image" src="https://github.com/user-attachments/assets/550552be-f612-425f-9fed-0241315cf814">
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/08568f2e-db75-4a05-aa38-c715601995f5">
