### ISSUE TITLE
[BUG] <title> hertzbeat-collector version:newest can not collect cpu info of Host Machine but only hertzbeat-collector's docker 

### ISSUE THREAD

**Issue by xiaoguolong** [apache/hertzbeat#2841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

最新的版本hertzbeat部署到宿主机192.168.16.43机器，并通过在另外一台机192.168.16.173机器部署最新版本hertzbeat-collector，用的是linux脚本模板
![image](https://github.com/user-attachments/assets/3f10c633-cebe-4fe3-a283-794f58f5a432)
![image](https://github.com/user-attachments/assets/fd41a3b5-f1f9-4b53-8d33-7cd89810e67a)
上面收集到的信息是进去collector容器里面进程信息
![image](https://github.com/user-attachments/assets/4893a890-2867-4243-80cf-eaec8f8d5cec)

### Expected Behavior

收集到宿主机上的CPU信息
![image](https://github.com/user-attachments/assets/bea5fb72-4c34-4918-b88b-db217bb3330d)

### Environment

```markdown
HertzBeat version(s):
```

**Comment by zuobiao-zhou** [comment]
Since Docker containers operate in an isolated environment, each container has its own process space. If the container is configured to share the PID namespace (using --pid=host), it can access the host's PID namespace, but this reduces security. If possible, it is recommended to deploy the collector by [downloading the hertzbeat-collector-xx.tar.gz package](https://hertzbeat.apache.org/docs/download/).

**Comment by xiaoguolong** [comment]
ok thanks  . I have a try of deploy of tar

**Comment by xiaoguolong** [comment]
![Uploading image.png…]()
thank you . use your point of deploy ,it's ok

> Since Docker containers operate in an isolated environment, each container has its own process space. If the container is configured to share the PID namespace (using --pid=host), it can access the host's PID namespace, but this reduces security. If possible, it is recommended to deploy the collector by [downloading the hertzbeat-collector-xx.tar.gz package](https://hertzbeat.apache.org/docs/download/).

**Comment by zuobiao-zhou** [comment]
> ![image](https://private-user-images.githubusercontent.com/33684988/391026447-0833b1c2-4435-4b0b-a227-abae841ded31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzEwOTAsIm5iZiI6MTczMjg3MDc5MCwicGF0aCI6Ii8zMzY4NDk4OC8zOTEwMjY0NDctMDgzM2IxYzItNDQzNS00YjBiLWEyMjctYWJhZTg0MWRlZDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA4NTk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NGFlYWJkNDNjYzY4ZGZjZGQ1Mzk0MTMzMjRhNDQwMmU4MzhkNjMwYTFhNDhlOWVmYzA4OWNkM2NhNGM5NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gQjBN55VtykUSHQ_fnCo4iJKy-6vBsB3vqwl9JqOWx4)
> 
> thank you . use your point of deploy ,it's ok
> 
> > Since Docker containers operate in an isolated environment, each container has its own process space. If the container is configured to share the PID namespace (using --pid=host), it can access the host's PID namespace, but this reduces security. If possible, it is recommended to deploy the collector by [downloading the hertzbeat-collector-xx.tar.gz package](https://hertzbeat.apache.org/docs/download/).

Thank you for your feedback. I had not fully considered this issue before. I will include relevant notes in the official documentation to better guide users.
