### ISSUE TITLE
[Question] custom plugin can't be upload

### ISSUE THREAD

**Issue by shirlly46** [apache/hertzbeat#2882]
### Question

我这里的需求是将告警后的信息传入到公司自己的业务系统中进行集中的通知，看了文档后选择了自定义插件的功能，但在我根据文档的要求编写打包后上传时，系统提示A plugin package can only contain one plugin implementation class，求教各位大神

版本如下：

- hertzbeat：1.6.1
- jdk：17.0.13
- maven：3.8.8

[issue.zip](https://github.com/user-attachments/files/18176608/issue.zip)

**Comment by shirlly46** [comment]
看了下源码，在PluginServiceImpl的229行这边的逻辑是否有待商榷，只要前面有插件的实现类，后面扫描到的class，只要不是接口，它都会走到throw的代码里。这就导致插件的实现类如果在前面被扫描，那么后面只要有类的class，那么都无法添加成功

**Comment by LiuTianyou** [comment]
@shirlly46  hi, to facilitate plugin management, currently the plugin function only supports a jar package containing an implementation class of a plugin interface. Please refer to the document https://hertzbeat.apache.org/docs/help/plugin/

**Comment by shirlly46** [comment]
thx
