### ISSUE TITLE
[Task] <title>Batch bind and remove tags for selected monitoring rows.

### ISSUE THREAD

**Issue by EvanderYang** [apache/hertzbeat#2884]
### Description

![image](https://github.com/user-attachments/assets/801be35a-e729-4703-8f12-ed3a1125f0b7)

**Comment by tomsun28** [comment]
hi, how to batch bang tag here

**Comment by tomsun28** [comment]
We are refactoring the tags, suggest consider whether to do this later.

**Comment by EvanderYang** [comment]
That's great, 
please make sure to implement the function of batch binding tags or removing monitoring items，
and i will close this issue later。
