### ISSUE TITLE
[Question] <title>Some optimization suggestions for Kafka client monitoring metrics.

### ISSUE THREAD

**Issue by doveLin0818** [apache/hertzbeat#2885]
### Question

Currently, Hertzbeat offers two methods for monitoring Kafka: one is based on the JMX protocol, and the other uses Kafka clients. For Kafka clients, I have two optimization suggestions:

1. In the "Topic Offset" module, the second column is intended to represent the partition number corresponding to the topic, not the number of partitions, as shown in the figure below. This can cause confusion for Chinese users. I suggest changing the title to "分区号" in the Chinese display. This would require modifying the monitoring template.
<img width="735" alt="image" src="https://github.com/user-attachments/assets/be0e1b39-30a8-4140-bdee-4e3370c64e97" />

2. Currently, Kafka client metrics are limited. I recommend adding a new module called "Consumer Group Status," which would include metrics such as consumer group ID, subscribed topic names, partition offsets, total consumption lag, and other related fields.

If necessary, I am willing to assist in implementing these changes.

**Comment by tomsun28** [comment]
+1👍 welcome to optimize this.
