### ISSUE TITLE
[BUG] Kafka-Client Chaotic monitoring indicators

### ISSUE THREAD

**Issue by weixiaochun1998** [apache/hertzbeat#2886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created two monitors using Kafka Client, one is 188 and the other is 189. The first one was created with 189 and the monitored indicators were normal. Then, when monitoring 188, the monitored indicators were all from the previous 189. The two Kafka are not in the same cluster
![image](https://github.com/user-attachments/assets/0f6a3aed-adda-4bf6-97cd-be3a98f80285)

### Environment

```markdown
HertzBeat version(1.6.1):
```

**Comment by Rancho-7** [comment]
Hi,

I think maybe the monitor that was just created does not have data yet,and the data is refreshed at intervals,so it's temporarily showing the monitor data that has been captured before?

May I ask if the problem still exists after refreshing it a few times at intervals?

**Comment by weixiaochun1998** [comment]
Hello, at first it was like this, there was no data. After a while, there was data, but the data was from the previous monitoring and it was chaotic
![image](https://github.com/user-attachments/assets/f98f8bf7-aba1-47f8-ab43-c88ee4c2bbab)

**Comment by zhangshenghang** [comment]
> Hello, at first it was like this, there was no data. After a while, there was data, but the data was from the previous monitoring and it was chaotic ![image](https://private-user-images.githubusercontent.com/108884213/397672195-f98f8bf7-aba1-47f8-ab43-c88ee4c2bbab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg0NjQsIm5iZiI6MTczNDc4ODE2NCwicGF0aCI6Ii8xMDg4ODQyMTMvMzk3NjcyMTk1LWY5OGY4YmY3LWFiYTEtNDdmOC1hYjQzLWM4OGVlNGMyYmJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMzM2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTg4NDAxOTc1ZDU5MzE1ZWRmMTY3NDU5YjExY2JiMDg5MzJjM2EwMTQ0ZWMzZjE5Mjg4ODUzNzE5ZjdjZmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K9ZMzWTaNznA1dsvNoEXjBsa7FV0yemFCWZTPMbjRqk)

Yes, this is a bug, we will fix it as soon as possible

**Comment by doveLin0818** [comment]
> > Hello, at first it was like this, there was no data. After a while, there was data, but the data was from the previous monitoring and it was chaotic ![image](https://private-user-images.githubusercontent.com/108884213/397672195-f98f8bf7-aba1-47f8-ab43-c88ee4c2bbab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODg0NjQsIm5iZiI6MTczNDc4ODE2NCwicGF0aCI6Ii8xMDg4ODQyMTMvMzk3NjcyMTk1LWY5OGY4YmY3LWFiYTEtNDdmOC1hYjQzLWM4OGVlNGMyYmJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMzM2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTg4NDAxOTc1ZDU5MzE1ZWRmMTY3NDU5YjExY2JiMDg5MzJjM2EwMTQ0ZWMzZjE5Mjg4ODUzNzE5ZjdjZmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K9ZMzWTaNznA1dsvNoEXjBsa7FV0yemFCWZTPMbjRqk)
> 
> Yes, this is a bug, we will fix it as soon as possible

@zhangshenghang Hi, perhaps In the method org.apache.hertzbeat.collector.collect.kafka.KafkaConnect#getAdminClient, the adminClient is not updated before and after modifying the monitoring instance, and the old adminClient is reused, which leads to this issue.see https://github.com/apache/hertzbeat/pull/2895 thanks
