### ISSUE TITLE
[Question] Message Notification - Notification Medium - Edit

### ISSUE THREAD

**Issue by Uin17** [apache/hertzbeat#2897]
### Question

列表中存在一列通知数据时，点击编辑后，修改了【配置】，但是点【取消】后，值还是被更新了，这个不知是已知问题还是特性呢？

**Comment by Uin17** [comment]
![image](https://github.com/user-attachments/assets/f3c59fb2-b513-48c2-8c7f-e0ff7fcd03f5)
![image](https://github.com/user-attachments/assets/92366393-d846-404d-836e-8c5e5fc1e972)
![image](https://github.com/user-attachments/assets/a3b370a4-c98d-4151-85dc-40da8d3eacb8)

**Comment by yunfan24** [comment]
It seems like a front-end page bug. After clicking "Cancel," the page displays as if it has been modified, but no request is sent to the back-end. Upon refreshing the page, it reverts to the original value.
Additionally, should clicking "Edit" re-request the back-end interface to fetch the latest value?
If any modifications are needed, feel free to assign them to me.
感觉像是前端页面的bug，点击取消后虽然页面显示已被修改，但是并未向后端发送请求，刷新页面后还会变成原来的值；
另外，点击编辑是否需要重新请求后端接口获得当前最新的值？
如果需要修改的话，可以指派给我。
![PixPin_2024-12-26_00-00-00](https://github.com/user-attachments/assets/2db8d342-9af6-4229-a305-85387e252dc8)

**Comment by tomsun28** [comment]
Hi, yes it is a bug, welcome to help us fix it. @yunfan24 has assigned to you
