### ISSUE TITLE
[Task] <add jasypt encryption tool with compatible>

### ISSUE THREAD

**Issue by QYG2297248353** [apache/hertzbeat#290]
### Description

# 加密插件[ jasypt-spring-boot-starter](https://github.com/ulisesbocchio/jasypt-spring-boot)
![image](https://user-images.githubusercontent.com/56836951/189879334-ce5100e8-23ee-4953-a5e8-20f757e75c73.png)

### 代码仓库明文保存密码是比较不安全的，建议对插件的兼容
# 配置
![image](https://user-images.githubusercontent.com/56836951/189879753-64193238-550c-4575-8325-68f05f90485b.png)
# 读取到源文件信息
![image](https://user-images.githubusercontent.com/56836951/189880079-93b97e1c-e7d1-4891-ac7f-7c155aeff737.png)
# 原因
![image](https://user-images.githubusercontent.com/56836951/189891536-7e1ee5db-bc21-483f-8d17-2e8ad1ff944d.png)

# 替代方案-已实现
环境变量+盐
![image](https://user-images.githubusercontent.com/56836951/189890447-53a929c4-c812-4985-8638-175ba419880b.png)

### Task List

一个小需求

**Comment by tomsun28** [comment]
👍👍👍 hi.  能提交个PR实现这个需求吗😊   

还有个有点小问题，这样能不能和之前的配置兼容？
