### ISSUE TITLE
希望自定义监控的自定义权限更高些

### ISSUE THREAD

**Issue by colo1994** [apache/hertzbeat#38]
1.很多开发人员，非专业的服务器运维人员，更多的时候是Free -h 后回去自己写正则等拼凑服务器，去用AWK 这些难度很大。希望可以将parseType 这里加个自定义，再可以用反射或者JS引擎 ，动态的解析命令，返回结果
2.采集的时候configmap 能不能写成一个配置数组或者map，协议那边直接写下标或者key去取，少点配置。
3.碰到一些综合的采集，比如先执行SSH,再执行SQL，甚至还会调一些HTTP请求的，这边能用反射拓展开放吗？

**Comment by tomsun28** [comment]
谢谢反馈很有用的建议  
> 1.很多开发人员，非专业的服务器运维人员，更多的时候是Free -h 后回去自己写正则等拼凑服务器，去用AWK 这些难度很大。
希望可以将parseType 这里加个自定义，再可以用反射或者JS引擎 ，动态的解析命令，返回结果 

这个可以有的，就是需要考虑怎么去调用实现解析脚本

> 2.采集的时候configmap 能不能写成一个配置数组或者map，协议那边直接写下标或者key去取，少点配置。 

这个已经在计划的支持中，目前configmap是key-value，但不能满足一些加header等场景，争取尽快支持。

> 3.碰到一些综合的采集，比如先执行SSH,再执行SQL，甚至还会调一些HTTP请求的，这边能用反射拓展开放吗？

你说的是一个监控类型比如MYSQL，可能需要采集ssh监控主机CPU内存，还需要执行SQL查询库指标这种场景吗，目前是已经支持了，在监控定义yml里面对不同的指标配置不同的采集协议就可以的。

**Comment by colo1994** [comment]
你好，关于第三点意思是这样子的。
是一些新型数据库的指标，不是单纯的JDBC就可以采集的。需要ssh+jdbc一起执行才可以，先去SSH执行一些指令拿到结果，再去jdbc里面拿结果，这样子的。
