### ISSUE TITLE
[BUG] <title> Direct access to the login page prompts an error

### ISSUE THREAD

**Issue by k4n5ha0** [apache/hertzbeat#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

输入 http://172.12.88.88:888  后
跳转到  http://172.12.88.88:888/passport/login

直接输入  http://172.12.88.88:888/passport/login
则显示页面错误
![image](https://user-images.githubusercontent.com/22064977/199437409-f3c9bb31-3401-457f-bfa0-b9ccdb41c021.png)

### Expected Behavior

直接输入  http://172.12.88.88:888/passport/login
应该能正常使用

### Environment

```markdown
HertzBeat version(s):1.1.3
```

**Comment by tomsun28** [comment]
你好 按着你的步骤在最新版本访问 `http://localhost:1157/passport/login` 我们没有复现此问题，看你的演示端口888 是你们自己改了啥导致这个问题的吗

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hello, follow your steps to visit `http://localhost:1157/passport/login` in the latest version. We have not reproduced this problem. Look at your demo port 888, did you change what caused this problem?
