### ISSUE TITLE
[Task] <Unit Test Case> com/usthe/alert/service/AlertService.java

### ISSUE THREAD

**Issue by tomsun28** [apache/hertzbeat#445]
### Description

Help us impl Unit Test For [com/usthe/alert/service/AlertService.java](https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/service/AlertServiceTest.java) 
     
You can learn and refer to the previous test cases impl.
1. controller example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java 
2. service example unit case:  https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/service/TagServiceTest.java
3. jpa sql dao example unit case: https://github.com/dromara/hertzbeat/blob/master/manager/src/test/java/com/usthe/manager/dao/MonitorDaoTest.java 

### Task List

- [ ]  Impl Unit Test For [com/usthe/alert/service/AlertService.java](https://github.com/dromara/hertzbeat/blob/master/alerter/src/test/java/com/usthe/alert/service/AlertServiceTest.java)

**Comment by i1619khz** [comment]
Please assign the task to me
