### ISSUE TITLE
升级脚本

### ISSUE THREAD

**Issue by Suremotoo** [apache/hertzbeat#78]
随着版本一次次升级，新增特性功能、Bug 修复等，涉及到数据库表的调整时，能一并提供数据库表的升级脚本，像我之前刚开始使用，觉得不错，维护了大量监控数据，现在咱们的数据库表结构有变化，我需要手动迁移数据，挺费时间的。

每次数据库调整时，能一并提供数据库与上一次的变化，虽然我可以将当前的数据库表结构导出，与新的数据库脚本对比，但是导出后顺序也不一样，最终还是要从提交记录上找到之前的，也挺费时间。

如果能在一并**提供数据库与上一次的变化**的同时，也一并**提供旧数据迁移的脚本**，会更好！

> 假如新数据表字段是必填等信息，可以给予默认值，当然的，我们也可以自行更改默认值！

**Comment by tomsun28** [comment]
Hi 感谢反馈 这个问题确实应该重视起来，目前最近的两个版本没有mysql对应的关系表结构变更，但是因为指标的修改新增，对应TDengine的表结构可能会发生变化，它的表是有数据时自动创建的，这块确实没有考虑周到，tdengine会影响历史图表数据展示。
后面我们研究下指标表这块的升级问题。

**Comment by Suremotoo** [comment]
感谢您的及时反馈！🙏🙏

我的就是升级至 **Beta 7** 后，首页监控表盘都是 0，且之前配置的 telnet 端口检测菜单没有了，不知道是不是取消了，我在 error log 文件中发现，凡是之前配置的 telnet 端口监控，全部都提示 **_The app telnet not support._**

如图：

[首页监控表盘无数据图]

<img width="1847" alt="首页监控表盘无数据图" src="https://user-images.githubusercontent.com/26423989/162383419-7ef1f975-11bf-4262-9aab-8a7f871f05e7.png">

[ telnet 端口无法检测提示图]
![telnet 端口无法检测提示图](https://user-images.githubusercontent.com/26423989/162383201-59fd0012-eaa5-4822-88f9-59f851aa9962.png)

**Comment by tomsun28** [comment]
hi 是因为之前telnet和port监控类型重复 删除了telnet导致 抱歉这个没有及时考虑到 
需要在数据库的monitor表app字段将telnet的类型应用改为port类型

**Comment by Suremotoo** [comment]
> hi 是因为之前 telnet 和 port 监控类型重复 删除了 telnet 导致 抱歉这个没有及时考虑到 需要在数据库的 monitor 表 app 字段将 telnet 的类型应用改为 port 类型

已经修正成功！感谢🙏

**Comment by gcdd1993** [comment]
@tomsun28 数据库版本可以使用SpringBoot集成Flyway，启动项目会校验数据库版本并执行更新（如果有的话）

**Comment by tonywen1990** [comment]
+1，建议升级提上日程。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
+1 for suggesting an upgrade be on the agenda.
