### ISSUE TITLE
[Feature] <Have you considered adding the service restart function>

### ISSUE THREAD

**Issue by zqr10159** [apache/hertzbeat#885]
### Question

背景：项目上需要进行内网监控，目前内网数据可以通过边界到互联网，也就是互联网可以收到监控告警，但是无法远程进入内网服务器。
需求：在监控告警时，连接目标服务器，发送指定重启服务的命令，避免小问题深夜到现场处理。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
### Question

Background: Intranet monitoring is required for the project. At present, intranet data can pass through the border to the Internet, that is, the Internet can receive monitoring alarms, but it cannot remotely access the intranet server.
Requirements: When monitoring alarms, connect to the target server and send a specified command to restart the service, avoiding minor problems to be dealt with on-site late at night.
